Memory Measurement Library (CPP): MemoryControllerSPI Class Reference
MemoryControllerSPI Class Reference
This class implements the communication with SPI based memory controllers. Currently the Fujitsu ReRAM MB85AS4MT an the ReRAM_Adesto_RM25C512C is supported.
#include <MemoryControllerSPI.h>
Data Structures
struct MemoryStatusRegister
This struct defines each register bit of the registers of the Adesto and Fujitsu ReRAM chip.
Public Types
enum SPI_Commands {
ReRAM_WREN = (uint8_t) 0x06 , ReRAM_WRDI = (uint8_t) 0x04 , ReRAM_RDSR = (uint8_t) 0x05 , ReRAM_WRSR = (uint8_t) 0x01 ,
ReRAM_READ = (uint8_t) 0x03 , ReRAM_WRITE = (uint8_t) 0x02 , ReRAM_PD = (uint8_t) 0x09 , ReRAM_UDPD = (uint8_t) 0x79 ,
ReRAM_RES = (uint8_t) 0xAB , ReRAM_RDID = (uint8_t) 0x9F , ReRAM_SLEEP = (uint8_t) 0xB9 , ReRam_PowerDown = (uint8_t) 0xAB
}
Public Member Functions
MemoryControllerSPI (SPIWrapper *interfaceWrapper, MemoryModule &memoryModule)
MEM_ERROR Write8BitWord (uint32_t address, uint8_t valueToWrite) override
Writes a single 8 bit valueToWrite to an address.
MEM_ERROR Read8BitWord (uint32_t address, uint8_t *readValue) override
Reads a single 8 bit value to an address.
MEM_ERROR Write16BitWord (uint32_t address, uint16_t valueToWrite) override
Function not supported!
MEM_ERROR Read16BitWord (uint32_t address, uint16_t *valueToRead) override
Function not supported!
MEM_ERROR WriteStatusRegister (MemoryStatusRegister &statusRegister)
This function writes the specified status register to the Memory chip.
MEM_ERROR ReadStatusRegister (MemoryStatusRegister &statusRegister)
This function reads the status register from the memory chip.
MEM_ERROR SetWriteEnableLatch (bool checkRegister, uint32_t timeoutInMs)
This function sets the write enable latch register.
MEM_ERROR Reset_WriteEnableLatch ()
This function resets the write enable latch register.
uint32_t PollWriteInProgressRegister (uint32_t timeoutCycles)
This method can be executed after a write operation. The write operation sets the write in progress bit to 1. This method uses busy waiting to constantly poll this register until it changes to 0, which means the write operation has finished.
MEM_ERROR SetPowerDown ()
Power Down mode allows the user to reduce the power of the device to its lowest power consumption state. All instructions given during the Power Down mode are ignored except the Resume from Power down (RES) instruction. Therefore this mode can be used as an additional software write protection feature.
MEM_ERROR ResumeFromPowerDown ()
The Resume from Power Down mode is the only command that will wake the device up from the Power Down mode. All other commands are ignored. In the simple instruction command, after the CS pin is brought low, the RES instruction is shifted in. At the end of the instruction, the CS pin is brought back high.
MEM_ERROR SetUltraDeepPowerDown ()
he Ultra-Deep Power Down mode allows the device to further reduce its energy consumption compared to the existing Standby and Power Down modes by shutting down additional internal circuitry. When the device is in the Ultra-Deep Power Down mode, all commands including the Read Status Register and Resume from Deep Power Down commands will be ignored. Since all commands will be ignored, the mode can be used as an extra protection mechanism against inadvertent or unintentional program and erase operations. Entering the Ultra-Deep Power Down mode is accomplished by simply asserting the CS pin, clocking in the opcode 79h, and then deasserting the CS pin. Any additional data clocked into the device after the opcode will be ignored. When the CS pin is deasserted, the device will enter the Ultra-Deep Power Down mode within the maximum time of t EUDPD .
MEM_ERROR SetSleepMode ()
MEM_ERROR EraseChip ()
Chip Erase sets all bits inside the device to a 1. A Write Enable (WREN) instruction is required prior to a Chip Erase. After the WREN instruction is shifted in, the CS pin must be brought high to set the Write Enable Latch.
MEM_ERROR SendSPICommand (SPI_Commands spiCMD, uint8_t *retValue, bool response)
Helper function which sends a simple command to the SPI interface. These commands only have one byte of payload, for example Resume from Power Down.
Public Member Functions inherited from MemoryController
MemoryController (InterfaceWrapper *interfaceWrapper, MemoryModule &memoryModule)
virtual ~MemoryController ()
virtual MEM_ERROR Initialize ()
virtual MEM_ERROR Write8BitWord (uint32_t adr, uint8_t value)
virtual MEM_ERROR Read8BitWord (uint32_t adr, uint8_t *ret)
virtual MEM_ERROR Write16BitWord (uint32_t adr, uint16_t value)
virtual MEM_ERROR Read16BitWord (uint32_t adr, uint16_t *value)
MEM_ERROR WriteSingleValue (uint32_t address, uint8_t value)
MEM_ERROR WriteSingleValue (uint32_t address, uint16_t value)
MEM_ERROR FillMemoryArea (uint32_t startAddress, uint32_t endAddress, uint8_t value)
MEM_ERROR FillMemoryArea (uint32_t startAddress, uint32_t endAddress, uint16_t value)
MEM_ERROR FillMemoryArea (uint32_t startAddress, uint32_t endAddress, uint8_t(*dataFunction)(uint32_t address))
MEM_ERROR FillMemoryArea (uint32_t startAddress, uint32_t endAddress, uint16_t(*dataFunction)(uint32_t address))
MEM_ERROR VerifyMemoryArea (uint32_t startAddress, uint32_t endAddress, uint16_t expectedValue)
MEM_ERROR VerifyMemoryArea (uint32_t startAddress, uint32_t endAddress, uint8_t expectedValue)
MEM_ERROR VerifyMemoryArea (uint32_t startAddress, uint32_t endAddress, uint8_t(*dataFunction)(uint32_t address))
MEM_ERROR VerifyMemoryArea (uint32_t startAddress, uint32_t endAddress, uint16_t(*dataFunction)(uint32_t address))
MEM_ERROR FillWithZeros ()
MEM_ERROR FillWithZerosAndVerifyRead ()
MEM_ERROR FillWithOnes ()
MEM_ERROR FillMemoryWithAscendingValues ()
MEM_ERROR FillMemoryWithAscendingValuesAndVerifyRead (uint32_t *buffLen, const uint32_t *arguments)
MEM_ERROR FillMemoryWithAlternatingZeroAndOne ()
MEM_ERROR FillMemoryWithAlternatingOneAndZero ()
Static Public Member Functions
static MemoryStatusRegister Uint8ToStatusRegister (uint8_t statusRegister)
static uint8_t StatusRegisterToUint8 (MemoryStatusRegister &memoryStatusRegister)
This function returns the statusregister struct into one byte which can be send to the memory.
static void PrintStatusRegister (MemoryStatusRegister reg)
Prints the status register TODO this should be implementet in a special formatter class.
Static Public Member Functions inherited from MemoryController
static bool IsInvalidAddress (uint32_t address, uint32_t size)
Private Attributes
SPIWrapper * m_SPIWrapper
Additional Inherited Members
Protected Member Functions inherited from MemoryController
void InitCounter ()
void InitArguments ()
Protected Attributes inherited from MemoryController
uint8_t write_mode
uint16_t len
char STRING_BUFFER [STRING_BUFFER_SIZE]
TimeMeasurement m_timeMeasurement
uint32_t m_MMIOStartAddress
InterfaceWrapper * m_InterfaceWrapper
uint16_t start_value = 0x0
uint32_t start_adr = 0x0
uint32_t end_adr = 0x0
char SRAM_BUFFER [40960] {}
char * srambp {}
uint32_t total_one
uint32_t total_zero
uint32_t flipped_one
uint32_t flipped_zero
MemoryModule & m_MemoryModule
Detailed Description
This class implements the communication with SPI based memory controllers. Currently the Fujitsu ReRAM MB85AS4MT an the ReRAM_Adesto_RM25C512C is supported.
Author
Florian Frank
Copyright
University of Passau - Chair of computer engineering
Definition at line 15 of file MemoryControllerSPI.h.
Member Enumeration Documentation
SPI_Commands
enum MemoryControllerSPI::SPI_Commands
Enumerator
ReRAM_WREN
Set Write Enable Latch
ReRAM_WRDI
Reset Write Enable Latch
ReRAM_RDSR
Read Status Register
ReRAM_WRSR
Write Status Register
ReRAM_READ
Read Memory Code
ReRAM_WRITE
Write Memory Code
ReRAM_PD
ReRAM_UDPD
Ultra Deep Power Down
ReRAM_RES
Resume from Power Down
ReRAM_RDID
Read Device ID
ReRAM_SLEEP
Sleep Mode
ReRam_PowerDown
allows the user to reduce the power of the device to its lowest power consumption state.
Definition at line 20 of file MemoryControllerSPI.h.
    {
        ReRAM_WREN = (uint8_t) 0x06,
        ReRAM_WRDI = (uint8_t) 0x04,
        ReRAM_RDSR = (uint8_t) 0x05,
        ReRAM_WRSR = (uint8_t) 0x01,
        ReRAM_READ = (uint8_t) 0x03,
        ReRAM_WRITE = (uint8_t) 0x02,
        ReRAM_PD        = (uint8_t) 0x09,       // TODO CHECK
        ReRAM_UDPD = (uint8_t) 0x79,
        ReRAM_RES = (uint8_t) 0xAB,
        ReRAM_RDID = (uint8_t) 0x9F,
        ReRAM_SLEEP = (uint8_t) 0xB9,
        ReRam_PowerDown = (uint8_t) 0xAB
    } typedef SPI_Commands;
Constructor & Destructor Documentation
MemoryControllerSPI()
MemoryControllerSPI::MemoryControllerSPI (SPIWrapper * interfaceWrapper, MemoryModule & memoryModule) explicit
Author
Florian Frank
Copyright
University of Passau - Chair of computer engineering
Definition at line 11 of file MemoryControllerSPI.cpp.
                                                                                                 : MemoryController(
        interfaceWrapper, memoryModule), m_SPIWrapper(interfaceWrapper)
{
    if(m_MemoryModule.GetConnectionType() != MemoryProperties::SPI)
    {
        // TODO exception
    }
    m_MemoryModule.Initialize();
}
References MemoryModule::GetConnectionType(), MemoryModule::Initialize(), MemoryController::m_MemoryModule, and MemoryProperties::SPI.
Member Function Documentation
EraseChip()
MEM_ERROR MemoryControllerSPI::EraseChip ()
Chip Erase sets all bits inside the device to a 1. A Write Enable (WREN) instruction is required prior to a Chip Erase. After the WREN instruction is shifted in, the CS pin must be brought high to set the Write Enable Latch.
Returns
MEM_NO_ERROR if the command was sent successfully.
Definition at line 318 of file MemoryControllerSPI.cpp.
{
    return SendSPICommand(ReRAM_PD, nullptr, false);
}
References ReRAM_PD, and SendSPICommand().
PollWriteInProgressRegister()
uint32_t MemoryControllerSPI::PollWriteInProgressRegister (uint32_t timeoutCycles)
This method can be executed after a write operation. The write operation sets the write in progress bit to 1. This method uses busy waiting to constantly poll this register until it changes to 0, which means the write operation has finished.
Parameters
timeoutCycles in case of an error and the WIP register doesn't change, this function returns with an error.
Returns
the amount of clock cycles required for WIP polling to flip from 1 to zero
Definition at line 246 of file MemoryControllerSPI.cpp.
{
    uint32_t endTS = 0;
    //start timer
    TimeMeasurement tm{};
    uint32_t startTS = tm.ResetAndStartTimer();
    do {
        MemoryStatusRegister statusRegister;
        MEM_ERROR err = ReadStatusRegister(statusRegister);
        if(err != MemoryErrorHandling::MEM_NO_ERROR )
            return err;
        if (statusRegister.WriteInProgressBit == 0) {
            return tm.StopTimer();
        }
        if(timeoutCycles != 0)
            endTS =tm.GetTimer();
    }while(startTS + timeoutCycles > endTS);
    return endTS;
}
References MemoryErrorHandling::MEM_NO_ERROR, ReadStatusRegister(), TimeMeasurement::ResetAndStartTimer(), and MemoryControllerSPI::MemoryStatusRegister::WriteInProgressBit.
PrintStatusRegister()
void MemoryControllerSPI::PrintStatusRegister (MemoryStatusRegister reg) static
Prints the status register TODO this should be implementet in a special formatter class.
Parameters
reg the status register which should be printed on the command line.
Definition at line 180 of file MemoryControllerSPI.cpp.
{
    printf("WP_Enable: %d\n"
           "Auto_Power_Down_Enable: %d\n"
           "Low_Power_Standby_Enable: %d\n"
           "Block_Protection_Bits: %d\n"
           "Write_Enable_Bits: %d\n"
           "Write_In_Progress_Bits: %d\n", reg.WriteProtectPin, reg.AutoPowerDownEnable, reg.LowPowerStandbyEnable,
           reg.BlockProtectionBits, reg.WriteEnableBit, reg.WriteInProgressBit);
}
References MemoryControllerSPI::MemoryStatusRegister::AutoPowerDownEnable, MemoryControllerSPI::MemoryStatusRegister::BlockProtectionBits, MemoryControllerSPI::MemoryStatusRegister::LowPowerStandbyEnable, MemoryControllerSPI::MemoryStatusRegister::WriteEnableBit, MemoryControllerSPI::MemoryStatusRegister::WriteInProgressBit, and MemoryControllerSPI::MemoryStatusRegister::WriteProtectPin.
Read16BitWord()
MEM_ERROR MemoryControllerSPI::Read16BitWord (uint32_t address, uint16_t * valueToRead) override virtual
Function not supported!
Parameters
address not used
valueToRead not used
Returns
MEM_INVALID_COMMAND
Reimplemented from MemoryController.
Definition at line 105 of file MemoryControllerSPI.cpp.
{
    if(m_MemoryModule.GetBitWidth() != 16)
        return MemoryErrorHandling::MEM_INVALID_COMMAND;
    else
        return MemoryErrorHandling::MEM_FUNCTION_NOT_IMPLEMENTED;
}
References MemoryModule::GetBitWidth(), MemoryController::m_MemoryModule, MemoryErrorHandling::MEM_FUNCTION_NOT_IMPLEMENTED, and MemoryErrorHandling::MEM_INVALID_COMMAND.
Read8BitWord()
MEM_ERROR MemoryControllerSPI::Read8BitWord (uint32_t address, uint8_t * readValue) override virtual
Reads a single 8 bit value to an address.
Parameters
address address from which data should be read.
readValue return value containing the read value.
Returns
MEM_NO_ERROR is write operation was successful otherwise an error code is returned.
Reimplemented from MemoryController.
Definition at line 56 of file MemoryControllerSPI.cpp.
{
    MEM_ERROR err = SetWriteEnableLatch(false, 0);
    if(err != MemoryErrorHandling::MEM_NO_ERROR)
        return err;
    uint8_t readData[4];
    uint16_t lenReadData = 4;
    err = m_MemoryModule.CreateReadMessage(address, readData, &lenReadData);;
    if(err != MemoryErrorHandling::MEM_NO_ERROR)
        return err;
    SPIWrapper::SetWriteProtect();
    err = m_SPIWrapper->SendData(readData, &lenReadData, 1000);
    SPIWrapper::ResetWriteProtect();
    if(err != MemoryErrorHandling::MEM_NO_ERROR)
        return err;
    uint8_t retData[2];
    uint16_t retDataSize = 2;
    err = m_SPIWrapper->ReceiveData(retData, &retDataSize, 1000);
    if(err != MemoryErrorHandling::MEM_NO_ERROR)
        return err;
    return MemoryErrorHandling::MEM_NO_ERROR;
}
References MemoryModule::CreateReadMessage(), MemoryController::m_MemoryModule, m_SPIWrapper, MemoryErrorHandling::MEM_NO_ERROR, SPIWrapper::ReceiveData(), SPIWrapper::ResetWriteProtect(), SPIWrapper::SendData(), SetWriteEnableLatch(), and SPIWrapper::SetWriteProtect().
ReadStatusRegister()
MEM_ERROR MemoryControllerSPI::ReadStatusRegister (MemoryStatusRegister & statusRegister)
This function reads the status register from the memory chip.
Parameters
statusRegister after a successfull execution, this variable contains the returned status register.
Returns
MEM_NO_ERROR is write operation was successful otherwise an error code is returned.
Definition at line 133 of file MemoryControllerSPI.cpp.
{
    uint8_t reg = 0;
    MEM_ERROR ret = SendSPICommand(ReRAM_RDSR, &reg, true);
    if (ret != MemoryErrorHandling::MEM_NO_ERROR)
        return ret;
    statusRegister = Uint8ToStatusRegister(reg);
    return MemoryErrorHandling::MEM_NO_ERROR;
}
References MemoryErrorHandling::MEM_NO_ERROR, ReRAM_RDSR, SendSPICommand(), and Uint8ToStatusRegister().
Referenced by PollWriteInProgressRegister(), and SetWriteEnableLatch().
Reset_WriteEnableLatch()
MEM_ERROR MemoryControllerSPI::Reset_WriteEnableLatch ()
This function resets the write enable latch register.
Returns
MEM_NO_ERROR if no error occurred otherwise return error code.
Definition at line 228 of file MemoryControllerSPI.cpp.
{
    SPIWrapper::SetWriteProtect();
    MEM_ERROR ret = SendSPICommand(ReRAM_WRDI, nullptr, false);
    SPIWrapper::ResetWriteProtect();
    if(ret != MemoryErrorHandling::MEM_NO_ERROR)
        return ret;
    return MemoryErrorHandling::MEM_NO_ERROR;
}
References MemoryErrorHandling::MEM_NO_ERROR, ReRAM_WRDI, SPIWrapper::ResetWriteProtect(), SendSPICommand(), and SPIWrapper::SetWriteProtect().
ResumeFromPowerDown()
MEM_ERROR MemoryControllerSPI::ResumeFromPowerDown ()
The Resume from Power Down mode is the only command that will wake the device up from the Power Down mode. All other commands are ignored. In the simple instruction command, after the CS pin is brought low, the RES instruction is shifted in. At the end of the instruction, the CS pin is brought back high.
Returns
MEM_NO_ERROR if the command was sent successfully.
Definition at line 286 of file MemoryControllerSPI.cpp.
{
    return SendSPICommand(ReRAM_RES, nullptr, false);
}
References ReRAM_RES, and SendSPICommand().
SendSPICommand()
MEM_ERROR MemoryControllerSPI::SendSPICommand (SPI_Commands spiCMD, uint8_t * retValue, bool response)
Helper function which sends a simple command to the SPI interface. These commands only have one byte of payload, for example Resume from Power Down.
Parameters
spiCMD command of the memory which should be sent.
retValue return value from the memory chip if the response flag is set.
response indicates if the function should wait for an response.
Returns
MEM_NO_ERROR if no error occurred otherwise return error code.
Definition at line 331 of file MemoryControllerSPI.cpp.
{
    if(response && !retValue)
        return MemoryErrorHandling::MEM_INVALID_ARGUMENT;
    auto cmd = (uint8_t)spiCMD;
    uint16_t size = 1;
    MEM_ERROR err = m_SPIWrapper->SendData(&cmd, &size, 10);
    size = 1;
    if(response || err != MemoryErrorHandling::MEM_NO_ERROR)
        m_SPIWrapper->ReceiveData(retValue, &size, 10);
    return err;
}
References m_SPIWrapper, MemoryErrorHandling::MEM_INVALID_ARGUMENT, MemoryErrorHandling::MEM_NO_ERROR, SPIWrapper::ReceiveData(), and SPIWrapper::SendData().
Referenced by EraseChip(), ReadStatusRegister(), Reset_WriteEnableLatch(), ResumeFromPowerDown(), SetPowerDown(), SetSleepMode(), SetUltraDeepPowerDown(), SetWriteEnableLatch(), and WriteStatusRegister().
SetPowerDown()
MEM_ERROR MemoryControllerSPI::SetPowerDown ()
Power Down mode allows the user to reduce the power of the device to its lowest power consumption state. All instructions given during the Power Down mode are ignored except the Resume from Power down (RES) instruction. Therefore this mode can be used as an additional software write protection feature.
Returns
MEM_NO_ERROR if the command was sent sucessfully.
Definition at line 275 of file MemoryControllerSPI.cpp.
{
    return SendSPICommand(ReRam_PowerDown, nullptr, false);
}
References ReRam_PowerDown, and SendSPICommand().
SetSleepMode()
MEM_ERROR MemoryControllerSPI::SetSleepMode ()
Definition at line 308 of file MemoryControllerSPI.cpp.
{
    return SendSPICommand(ReRAM_SLEEP, nullptr, false);
}
References ReRAM_SLEEP, and SendSPICommand().
SetUltraDeepPowerDown()
MEM_ERROR MemoryControllerSPI::SetUltraDeepPowerDown ()
he Ultra-Deep Power Down mode allows the device to further reduce its energy consumption compared to the existing Standby and Power Down modes by shutting down additional internal circuitry. When the device is in the Ultra-Deep Power Down mode, all commands including the Read Status Register and Resume from Deep Power Down commands will be ignored. Since all commands will be ignored, the mode can be used as an extra protection mechanism against inadvertent or unintentional program and erase operations. Entering the Ultra-Deep Power Down mode is accomplished by simply asserting the CS pin, clocking in the opcode 79h, and then deasserting the CS pin. Any additional data clocked into the device after the opcode will be ignored. When the CS pin is deasserted, the device will enter the Ultra-Deep Power Down mode within the maximum time of t EUDPD .
Returns
MEM_NO_ERROR if the command was sent successfully.
Definition at line 302 of file MemoryControllerSPI.cpp.
{
    return SendSPICommand(ReRAM_UDPD, nullptr, false);
}
References ReRAM_UDPD, and SendSPICommand().
SetWriteEnableLatch()
MEM_ERROR MemoryControllerSPI::SetWriteEnableLatch (bool checkRegister, uint32_t timeoutInMs)
This function sets the write enable latch register.
Parameters
checkRegister flag if the function should check if the register is set.
Returns
MEM_NO_ERROR if no error occurred otherwise return error code.
Definition at line 197 of file MemoryControllerSPI.cpp.
{
    SPIWrapper::SetWriteProtect();
    MEM_ERROR ret = SendSPICommand(ReRAM_WREN, nullptr, false);
    SPIWrapper::ResetWriteProtect();
    if(ret != MemoryErrorHandling::MEM_NO_ERROR)
        return ret;
    if(checkRegister)
    {
        MemoryStatusRegister statusRegister;
        TimeMeasurement tm{};
        uint32_t timeStampStart = TimeMeasurement::TransformClockFrequencyToMs(tm.ResetAndStartTimer());
        do
        {
            if(tm.GetElapsedTimeInMS() - timeStampStart > timeoutInMs)
                return MemoryErrorHandling::MEM_HAL_TIMEOUT;
            MEM_ERROR err = ReadStatusRegister(statusRegister);
            if (err != MemoryErrorHandling::MEM_NO_ERROR)
                return err;
        }while(statusRegister.WriteEnableBit != 1);
        //return MEM_REGISTER_NOT_SET;
    }
    return MemoryErrorHandling::MEM_NO_ERROR;
}
References MemoryErrorHandling::MEM_HAL_TIMEOUT, MemoryErrorHandling::MEM_NO_ERROR, ReadStatusRegister(), ReRAM_WREN, SPIWrapper::ResetWriteProtect(), SendSPICommand(), SPIWrapper::SetWriteProtect(), TimeMeasurement::TransformClockFrequencyToMs(), and MemoryControllerSPI::MemoryStatusRegister::WriteEnableBit.
Referenced by Read8BitWord(), and Write8BitWord().
StatusRegisterToUint8()
uint8_t MemoryControllerSPI::StatusRegisterToUint8 (MemoryStatusRegister & memoryStatusRegister) static
This function returns the statusregister struct into one byte which can be send to the memory.
Parameters
memoryStatusRegister the status register which is transformed into byte representation.
Returns
the status register in byte representation.
Definition at line 158 of file MemoryControllerSPI.cpp.
{
    uint8_t retValue = 0;
    if (memoryStatusRegister.WriteProtectPin != 0)
        retValue += 0x80;
    if (memoryStatusRegister.AutoPowerDownEnable != 0)
        retValue += 0x40;
    if (memoryStatusRegister.LowPowerStandbyEnable != 0)
        retValue += 0x20;
    if (memoryStatusRegister.BlockProtectionBits != 0)
        retValue += memoryStatusRegister.BlockProtectionBits;
    if (memoryStatusRegister.WriteEnableBit != 0)
        retValue += 0x02;
    if (memoryStatusRegister.WriteEnableBit != 0)
        retValue += 0x01;
    return retValue;
}
References MemoryControllerSPI::MemoryStatusRegister::AutoPowerDownEnable, MemoryControllerSPI::MemoryStatusRegister::BlockProtectionBits, MemoryControllerSPI::MemoryStatusRegister::LowPowerStandbyEnable, MemoryControllerSPI::MemoryStatusRegister::WriteEnableBit, and MemoryControllerSPI::MemoryStatusRegister::WriteProtectPin.
Referenced by WriteStatusRegister().
Uint8ToStatusRegister()
MemoryControllerSPI::MemoryStatusRegister MemoryControllerSPI::Uint8ToStatusRegister (uint8_t statusRegister) static
Definition at line 143 of file MemoryControllerSPI.cpp.
{
    return {static_cast<uint8_t>((statusRegister & 128) >> 7),
                                   static_cast<uint8_t>((statusRegister & 64) >> 6),
                                   static_cast<uint8_t>((statusRegister & 32) >> 5),
                                   static_cast<uint8_t>((statusRegister & 12) >> 2),
                                   static_cast<uint8_t>((statusRegister & 2) >> 1),
                                   static_cast<uint8_t>((statusRegister & 1))};
}
Referenced by ReadStatusRegister().
Write16BitWord()
MEM_ERROR MemoryControllerSPI::Write16BitWord (uint32_t address, uint16_t valueToWrite) override virtual
Function not supported!
Parameters
address not used
valueToWrite not used
Returns
MEM_INVALID_COMMAND
Reimplemented from MemoryController.
Definition at line 91 of file MemoryControllerSPI.cpp.
{
    if(m_MemoryModule.GetBitWidth() != 16)
        return MemoryErrorHandling::MEM_INVALID_COMMAND;
    else
        return MemoryErrorHandling::MEM_FUNCTION_NOT_IMPLEMENTED;
}
References MemoryModule::GetBitWidth(), MemoryController::m_MemoryModule, MemoryErrorHandling::MEM_FUNCTION_NOT_IMPLEMENTED, and MemoryErrorHandling::MEM_INVALID_COMMAND.
Write8BitWord()
MEM_ERROR MemoryControllerSPI::Write8BitWord (uint32_t address, uint8_t valueToWrite) override virtual
Writes a single 8 bit valueToWrite to an address.
Parameters
address address to write.
valueToWrite valueToWrite to write.
Returns
MEM_NO_ERROR is write operation was successful otherwise an error code is returned.
Reimplemented from MemoryController.
Definition at line 27 of file MemoryControllerSPI.cpp.
{
    MEM_ERROR err = SetWriteEnableLatch(false, 0);
    if (err != MemoryErrorHandling::MEM_NO_ERROR)
        return err;
    uint8_t sendBuffer[8];
    uint16_t sendBufferLen = 8;
    MEM_ERROR ret = m_MemoryModule.CreateWriteMessage(address, valueToWrite, sendBuffer, &sendBufferLen);
    if (ret != MemoryErrorHandling::MEM_NO_ERROR)
        return ret;
    SPIWrapper::SetWriteProtect();
    err = m_SPIWrapper->SendData(sendBuffer, &sendBufferLen, 10000);
    SPIWrapper::ResetWriteProtect();
    if (err != MemoryErrorHandling::MEM_NO_ERROR)
        return err;
    return MemoryErrorHandling::MEM_NO_ERROR;
}
References MemoryModule::CreateWriteMessage(), MemoryController::m_MemoryModule, m_SPIWrapper, MemoryErrorHandling::MEM_NO_ERROR, SPIWrapper::ResetWriteProtect(), SPIWrapper::SendData(), SetWriteEnableLatch(), and SPIWrapper::SetWriteProtect().
WriteStatusRegister()
MEM_ERROR MemoryControllerSPI::WriteStatusRegister (MemoryStatusRegister & statusRegister)
This function writes the specified status register to the Memory chip.
Parameters
statusRegister the register which should be written.
Returns
MEM_NO_ERROR is write operation was successful otherwise an error code is returned.
Definition at line 118 of file MemoryControllerSPI.cpp.
{
    uint8_t reg = StatusRegisterToUint8(statusRegister);
    MEM_ERROR ret = SendSPICommand(ReRAM_WRSR, &reg, true);
    if (ret != MemoryErrorHandling::MEM_NO_ERROR)
        return ret;
    return MemoryErrorHandling::MEM_NO_ERROR;
}
References MemoryErrorHandling::MEM_NO_ERROR, ReRAM_WRSR, SendSPICommand(), and StatusRegisterToUint8().
Field Documentation
m_SPIWrapper
SPIWrapper* MemoryControllerSPI::m_SPIWrapper private
Definition at line 92 of file MemoryControllerSPI.h.
Referenced by Read8BitWord(), SendSPICommand(), and Write8BitWord().
The documentation for this class was generated from the following files:
/home/florianfrank/Documents/Research/Projects/PUFMem/stm_measurement_firmware/Inc/cpp/MemoryControllers/MemoryControllerSPI.h
/home/florianfrank/Documents/Research/Projects/PUFMem/stm_measurement_firmware/Src/cpp/MemoryController/MemoryControllerSPI.cpp