Memory Measurement Library (CPP): /home/florianfrank/Documents/Research/Projects/PUFMem/stm_measurement_firmware/Src/cpp/Main/Main.cpp File Reference
Main.cpp File Reference
#include <cpp/MemoryControllers/MemoryControllerSPI.h>
#include <cstdio>
#include <cpp/InterfaceWrappers/UARTWrapper.h>
#include <cstring>
#include <cpp/Devices/STM32F429Wrapper.h>
#include <cpp/MemoryModules/ReRAM_ADESTO_RM25C512C_LTAI_T.h>
#include <cpp/MemoryControllers/MemoryControllerParallel.h>
#include "cpp/Main/Main.h"
#include "cpp/MemoryControllers/MemoryController.h"
#include "cpp/MemoryTest.h"
Macros
#define USE_USB_CDC
Functions
int main ()
The application entry point.
Variables
bool running = true
Macro Definition Documentation
USE_USB_CDC
#define USE_USB_CDC
Definition at line 21 of file Main.cpp.
Function Documentation
main()
int main ()
The application entry point.
Return values
int
Definition at line 27 of file Main.cpp.
{
#if STM32
    STM32F429Wrapper device;
    device.Initialize();
#endif
    RERAM_ADESTO_RM25C512C_LTAI_T fram;
    MemoryControllerParallel memoryController(nullptr, fram);
    memoryController.Initialize();
/*    for (uint32_t i = 0; i < fram.GetMemorySize(); i++)
    {
        memoryController.Write8BitWord(i, 0xFF);
        HAL_Delay(10);
    }*/
    uint8_t retValue = 0x00;
    for (uint32_t i = 0; i < fram.GetMemorySize(); i++)
    {
        memoryController.Read8BitWord(i, &retValue);
    }
    /* USER CODE END 3 */
}
References MemoryModule::GetMemorySize(), MemoryControllerParallel::Initialize(), and MemoryControllerParallel::Read8BitWord().
Variable Documentation
running
bool running = true
Author
Florian Frank
Copyright
University of Passau - Chair of computer engineering
Definition at line 18 of file Main.cpp.