Memory Measurement Library (CPP): MemoryControllerParallel Class Reference
MemoryControllerParallel Class Reference
This class is used to read and write to memory modules with a parallel connection. Currently this class supports writing to memory modules using a STM32F429DISC1 board using memory mapped IO.
#include <MemoryControllerParallel.h>
Public Member Functions
MemoryControllerParallel (InterfaceWrapper *interfaceWrapper, MemoryModule &memoryModule)
MEM_ERROR Initialize () override
MEM_ERROR Write8BitWord (uint32_t adr, uint8_t value) override
This function writes a 8 bit value to the passed address. Currently only a STM32F429DISC1 board is supported, which writes values using memory mapped IO.
MEM_ERROR Read8BitWord (uint32_t adr, uint8_t *retValue) override
This function reads an 8 bit value from a passed address. Currently only a STM32F429DISC1 board is supported, which reads values using memory mapped IO.
MEM_ERROR Write16BitWord (uint32_t adr, uint16_t value) override
This function writes a 16 bit value to the passed address. Currently only a STM32F429DISC1 board is supported, which writes values using memory mapped IO.
MEM_ERROR Read16BitWord (uint32_t adr, uint16_t *value) override
This function reads an 16 bit value from a passed address. Currently only a STM32F429DISC1 board is supported, which reads values using memory mapped IO.
Public Member Functions inherited from MemoryController
MemoryController (InterfaceWrapper *interfaceWrapper, MemoryModule &memoryModule)
virtual ~MemoryController ()
virtual MEM_ERROR Initialize ()
virtual MEM_ERROR Write8BitWord (uint32_t adr, uint8_t value)
virtual MEM_ERROR Read8BitWord (uint32_t adr, uint8_t *ret)
virtual MEM_ERROR Write16BitWord (uint32_t adr, uint16_t value)
virtual MEM_ERROR Read16BitWord (uint32_t adr, uint16_t *value)
MEM_ERROR WriteSingleValue (uint32_t address, uint8_t value)
MEM_ERROR WriteSingleValue (uint32_t address, uint16_t value)
MEM_ERROR FillMemoryArea (uint32_t startAddress, uint32_t endAddress, uint8_t value)
MEM_ERROR FillMemoryArea (uint32_t startAddress, uint32_t endAddress, uint16_t value)
MEM_ERROR FillMemoryArea (uint32_t startAddress, uint32_t endAddress, uint8_t(*dataFunction)(uint32_t address))
MEM_ERROR FillMemoryArea (uint32_t startAddress, uint32_t endAddress, uint16_t(*dataFunction)(uint32_t address))
MEM_ERROR VerifyMemoryArea (uint32_t startAddress, uint32_t endAddress, uint16_t expectedValue)
MEM_ERROR VerifyMemoryArea (uint32_t startAddress, uint32_t endAddress, uint8_t expectedValue)
MEM_ERROR VerifyMemoryArea (uint32_t startAddress, uint32_t endAddress, uint8_t(*dataFunction)(uint32_t address))
MEM_ERROR VerifyMemoryArea (uint32_t startAddress, uint32_t endAddress, uint16_t(*dataFunction)(uint32_t address))
MEM_ERROR FillWithZeros ()
MEM_ERROR FillWithZerosAndVerifyRead ()
MEM_ERROR FillWithOnes ()
MEM_ERROR FillMemoryWithAscendingValues ()
MEM_ERROR FillMemoryWithAscendingValuesAndVerifyRead (uint32_t *buffLen, const uint32_t *arguments)
MEM_ERROR FillMemoryWithAlternatingZeroAndOne ()
MEM_ERROR FillMemoryWithAlternatingOneAndZero ()
Additional Inherited Members
Static Public Member Functions inherited from MemoryController
static bool IsInvalidAddress (uint32_t address, uint32_t size)
Protected Member Functions inherited from MemoryController
void InitCounter ()
void InitArguments ()
Protected Attributes inherited from MemoryController
uint8_t write_mode
uint16_t len
char STRING_BUFFER [STRING_BUFFER_SIZE]
TimeMeasurement m_timeMeasurement
uint32_t m_MMIOStartAddress
InterfaceWrapper * m_InterfaceWrapper
uint16_t start_value = 0x0
uint32_t start_adr = 0x0
uint32_t end_adr = 0x0
char SRAM_BUFFER [40960] {}
char * srambp {}
uint32_t total_one
uint32_t total_zero
uint32_t flipped_one
uint32_t flipped_zero
MemoryModule & m_MemoryModule
Detailed Description
This class is used to read and write to memory modules with a parallel connection. Currently this class supports writing to memory modules using a STM32F429DISC1 board using memory mapped IO.
Author
Florian Frank
Copyright
University of Passau - Chair of computer engineering
Definition at line 14 of file MemoryControllerParallel.h.
Constructor & Destructor Documentation
MemoryControllerParallel()
MemoryControllerParallel::MemoryControllerParallel (InterfaceWrapper * interfaceWrapper, MemoryModule & memoryModule) explicit
Author
Florian Frank
Copyright
University of Passau - Chair of computer engineering
Definition at line 13 of file MemoryControllerParallel.cpp.
        : MemoryController(interfaceWrapper, memoryModule)
{
}
Member Function Documentation
Initialize()
MEM_ERROR MemoryControllerParallel::Initialize () override virtual
Reimplemented from MemoryController.
Definition at line 18 of file MemoryControllerParallel.cpp.
{
#if STM32
    MX_FMC_Init();
#endif // STM32
    return MemoryErrorHandling::MEM_NO_ERROR;
}
References MemoryErrorHandling::MEM_NO_ERROR.
Referenced by main().
Read16BitWord()
MEM_ERROR MemoryControllerParallel::Read16BitWord (uint32_t adr, uint16_t * value) override virtual
This function reads an 16 bit value from a passed address. Currently only a STM32F429DISC1 board is supported, which reads values using memory mapped IO.
Parameters
adr address to read from.
value the value to be read. Add a pointer as argument to retrieve the data.
Returns
MEM_NO_ERROR if write execution was successful. An error is returned if the address is invalid.
Reimplemented from MemoryController.
Definition at line 100 of file MemoryControllerParallel.cpp.
{
    if(IsInvalidAddress(adr, 10 /*TODO*/))
        return MemoryErrorHandling::MEM_INVALID_ADDRESS;
    if(!value)
        return MemoryErrorHandling::MEM_INVALID_ARGUMENT;
    // multiply address by 2 due to 2-byte-access (address is given as one byte)
    adr = adr << 1;
#if STM32
    *value = *(__IO uint16_t *) (m_MMIOStartAddress + adr);
#endif // STM32
    return MemoryErrorHandling::MEM_NO_ERROR;
}
References __IO, MemoryController::IsInvalidAddress(), MemoryController::m_MMIOStartAddress, MemoryErrorHandling::MEM_INVALID_ADDRESS, MemoryErrorHandling::MEM_INVALID_ARGUMENT, and MemoryErrorHandling::MEM_NO_ERROR.
Read8BitWord()
MEM_ERROR MemoryControllerParallel::Read8BitWord (uint32_t adr, uint8_t * ret) override virtual
This function reads an 8 bit value from a passed address. Currently only a STM32F429DISC1 board is supported, which reads values using memory mapped IO.
Parameters
adr address to read from.
ret the value which is returned after the reading operation.
Returns
MEM_NO_ERROR if write execution was successful. An error is returned if the address is invalid.
Reimplemented from MemoryController.
Definition at line 52 of file MemoryControllerParallel.cpp.
{
    if (IsInvalidAddress(adr, m_MemoryModule.GetMemorySize()))
        return MemoryErrorHandling::MEM_INVALID_ADDRESS;
    if(!ret)
        return MemoryErrorHandling::MEM_INVALID_ARGUMENT;
#if STM32
    *ret = *(__IO uint8_t *) (m_MMIOStartAddress + adr);
    if(*ret != 255)
        printf("RET %x: %x\n", adr, *ret);
#endif // STM32
    return MemoryErrorHandling::MEM_NO_ERROR;
}
References __IO, MemoryModule::GetMemorySize(), MemoryController::IsInvalidAddress(), MemoryController::m_MemoryModule, MemoryController::m_MMIOStartAddress, MemoryErrorHandling::MEM_INVALID_ADDRESS, MemoryErrorHandling::MEM_INVALID_ARGUMENT, and MemoryErrorHandling::MEM_NO_ERROR.
Referenced by main().
Write16BitWord()
MEM_ERROR MemoryControllerParallel::Write16BitWord (uint32_t adr, uint16_t value) override virtual
This function writes a 16 bit value to the passed address. Currently only a STM32F429DISC1 board is supported, which writes values using memory mapped IO.
Parameters
adr address to write the value.
value the value to write to the specified address.
Returns
MEM_NO_ERROR if write execution was successful. An error is returned if the address is invalid.
Reimplemented from MemoryController.
Definition at line 76 of file MemoryControllerParallel.cpp.
{
    if(IsInvalidAddress(adr, 10 /*TODO*/))
        return MemoryErrorHandling::MEM_INVALID_ADDRESS;
    // multiply address by 2 due to 2-byte-access (address is given as one byte)
    adr = adr << 1;
#if STM32
    *(__IO uint16_t *) (MEMORY_BANK_ADDRESS + adr) = value;
#endif // STM32
    return MemoryErrorHandling::MEM_NO_ERROR;
}
References __IO, MemoryController::IsInvalidAddress(), MemoryErrorHandling::MEM_INVALID_ADDRESS, and MemoryErrorHandling::MEM_NO_ERROR.
Write8BitWord()
MEM_ERROR MemoryControllerParallel::Write8BitWord (uint32_t adr, uint8_t value) override virtual
This function writes a 8 bit value to the passed address. Currently only a STM32F429DISC1 board is supported, which writes values using memory mapped IO.
Parameters
adr address to write the value.
value the value to write to the specified address.
Returns
MEM_NO_ERROR if write execution was successful. An error is returned if the address is invalid.
Reimplemented from MemoryController.
Definition at line 34 of file MemoryControllerParallel.cpp.
{
    if (IsInvalidAddress(adr, m_MemoryModule.GetMemorySize()))
        return MemoryErrorHandling::MEM_INVALID_ADDRESS;
#if STM32
    *(__IO uint8_t *) (m_MMIOStartAddress + adr) = value;
#endif // STM32
    return MemoryErrorHandling::MEM_NO_ERROR;
}
References __IO, MemoryModule::GetMemorySize(), MemoryController::IsInvalidAddress(), MemoryController::m_MemoryModule, MemoryController::m_MMIOStartAddress, MemoryErrorHandling::MEM_INVALID_ADDRESS, and MemoryErrorHandling::MEM_NO_ERROR.
The documentation for this class was generated from the following files:
/home/florianfrank/Documents/Research/Projects/PUFMem/stm_measurement_firmware/Inc/cpp/MemoryControllers/MemoryControllerParallel.h
/home/florianfrank/Documents/Research/Projects/PUFMem/stm_measurement_firmware/Src/cpp/MemoryController/MemoryControllerParallel.cpp