Memory Measurement Library (CPP): CommandLineParser Class Reference
CommandLineParser Class Reference
#include <CommandLineParser.h>
Public Member Functions
CommandLineParser (MemoryController *memoryController, InterfaceWrapper *commmunicationInterface)
void showHelp (uint8_t *inBuff, uint32_t *buffLen)
MEM_ERROR executeCommand (uint8_t *inBuff, uint32_t *inBuffLen, uint8_t *outBuff, uint32_t *outBufflen, Command cmdIdx)
Private Member Functions
CommandLineParser ()=default
Private Attributes
Command m_commandMode = NOPE
uint32_t m_arguments [3]
uint8_t m_WriteMode = 0xFF
uint16_t len
uint16_t old_len
char Rx_Buffer [100]
MemoryController * m_MemoryController
char m_SendBuffer [STRING_BUFFER_SIZE]
InterfaceWrapper * m_InterfaceWrapper
Static Private Attributes
static const char * command_help []
static const char * command []
Detailed Description
Author
Florian Frank
Copyright
University of Passau - Chair of computer engineering
Definition at line 19 of file CommandLineParser.h.
Constructor & Destructor Documentation
CommandLineParser() [1/2]
CommandLineParser::CommandLineParser (MemoryController * memoryController, InterfaceWrapper * commmunicationInterface) explicit
Definition at line 48 of file CommandLineParser.cpp.
{
    m_InterfaceWrapper = inputInterface;
}
References m_InterfaceWrapper.
CommandLineParser() [2/2]
CommandLineParser::CommandLineParser () private default
Member Function Documentation
executeCommand()
MEM_ERROR CommandLineParser::executeCommand (uint8_t * inBuff, uint32_t * inBuffLen, uint8_t * outBuff, uint32_t * outBufflen, Command cmdIdx)
Definition at line 74 of file CommandLineParser.cpp.
{
    MEM_ERROR ret = MemoryErrorHandling::MEM_NO_ERROR;
    switch(cmdIdx){
        case SHOW_HELP:
            // no write operation will be performed in this method
            //m_WriteMode = 0xFF;
            showHelp(outBuff, outBuffLen);
        case FILL_WITH_ZEROS:
            ret = m_MemoryController->FillWithZeros();
        case FILL_WITH_ONES:
            ret = m_MemoryController->FillWithOnes();
        case WRITE_ASCENDING:
            ret = m_MemoryController->FillMemoryWithAscendingValues();
        case WRITE_ALTERNATE_ZERO_ONE:
            ret = m_MemoryController->FillMemoryWithAlternatingZeroAndOne();
        case WRITE_ALTERNATE_ONE_ZERO:
            ret = m_MemoryController->FillMemoryWithAlternatingOneAndZero();
        case WRITE_ADDRESS:
            //ret = m_MemoryController->Write(outBuff, outBuffLen, m_arguments); TODO
        case WRITE_ADDRESS_RANGE:
            // write operation in mode 7 will be performed in this method
            // therefore reset the counters/m_arguments
            // they will be set in the function
            m_WriteMode = 0x7;
          //  return m_MemoryController->WriteAddressRange();TODO
        case GET_ADDRESS:
            // no write operation will be performed in this method
            // reset the counter for statistical analysis
            //m_WriteMode = 0xFF;
      //      return m_MemoryController->GetValueAndAddress(outBuff, outBuffLen, m_arguments);TODO
        case READ:
            // no write operation will be performed in this method
            //m_WriteMode = 0xFF;
            //return m_MemoryController->ReadWholeMemory(outBuff, outBuffLen);TODO
        case WRITE:
            // no write operation will be performed in this method
            //m_WriteMode = 0xFF;
            //return m_MemoryController->CheckReadWriteStatus(outBuff, outBuffLen); TODO
        case CHECK_ADDRESS:
            // no write operation will be performed in this method
            //m_WriteMode = 0xFF;
            //return m_MemoryController->CheckExpectedValueAtAddress(outBuff, outBuffLen, m_arguments);TODO
        case CHECK_ADDRESS_RANGE:
            // no write operation will be performed in this method
            //m_WriteMode = 0xFF;
            //return m_MemoryController->CheckExpectedValueAtAddressRange(outBuff, outBuffLen, m_arguments);TODO
        case GET_VALUES:
            //return m_MemoryController->ReadArea(outBuff, outBuffLen);TODO
        default:
            sprintf(m_SendBuffer, "Command not found. Type 'help' to show all valid commands.\n\n\r");
            len = strlen(m_SendBuffer);
            m_InterfaceWrapper->SendData(reinterpret_cast<uint8_t*>(m_SendBuffer), &len, 100);
            return ret;
    }
}
References MemoryController::FillMemoryWithAlternatingOneAndZero(), MemoryController::FillMemoryWithAlternatingZeroAndOne(), MemoryController::FillMemoryWithAscendingValues(), MemoryController::FillWithOnes(), MemoryController::FillWithZeros(), len, m_InterfaceWrapper, m_MemoryController, m_SendBuffer, m_WriteMode, MemoryErrorHandling::MEM_NO_ERROR, InterfaceWrapper::SendData(), and showHelp().
showHelp()
void CommandLineParser::showHelp (uint8_t * inBuff, uint32_t * buffLen)
Definition at line 59 of file CommandLineParser.cpp.
{
    uint32_t buffLen;
    sprintf((char*)buffer, "\rThis program provides the following commands:\n\n\r");
    buffLen = strlen((char*)buffer);
//  send(huart, (uint8_t *)m_SendBuffer, buffLen);
    for(uint8_t i = 0; i < COMMAND_COUNT; i++){
        sprintf((char*)&(buffer[buffLen]), "%s\r\n", command_help[i]);
        buffLen = strlen((char*)buffer);
        *bufferLen = buffLen;
        // TODO check bufferLen
        //send(huart, (uint8_t *)m_SendBuffer, buffLen);
    }
}
References COMMAND_COUNT, and command_help.
Referenced by executeCommand().
Field Documentation
command
const char * CommandLineParser::command static private
Initial value:
= {
    "help",
    "0",
    "1",
    "writeValueAsc",
    "writeAlternateZeroOne",
    "writeAlternateOneZero",
    "writeSRAM",
    "writeSRAMRange",
    "getPerformanceMeasures",
    "getAddress",
    "readSRAM",
    "checkSRAM",
    "checkAddress",
    "checkAddressRange",
    "v"
}
Author
Florian Frank
Copyright
University of Passau - Chair of computer engineering
Definition at line 42 of file CommandLineParser.h.
command_help
const char * CommandLineParser::command_help static private
Initial value:
= {
        "'help' Shows this site\r",
        "'0' writes 0's to the whole SRAM\r",
        "'1' writes 1's to the whole SRAM\r",
        "'writeValueAsc val' writes the 8/16-bit value 'val' to the first address and increments the value by 1\r",
        "'writeAlternateZeroOne' writes alternating 01010101... to the whole SRAM\r",
        "'writeAlternateOneZero' writes alternating 10101010... to the whole SRAM\r",
        "'writeSRAM adr val' writes the 8/16-bit value 'val' to address 'adr'\r",
        "'writeSRAMRange start end val' writes the 8/16-bit value 'val' to addresses 'start' to 'end'\r",
        "'getPerformanceMeasures' returns the probabilities P(0->1), P(1->0) and total flip probability (= HammingDistance / SRAM_size)\r",
        "'getAddress adr' returns the value at the address 'adr'\r",
        "'readSRAM' prints the whole content of the SRAM as hexadecimal value to the console (use Putty-logging for file-saving)\r",
        "'checkSRAM' checks, whether the expected value matches the real values of the whole SRAM\r",
        "'checkAddress adr val' checks, whether the value 'val' is equal to the content at address 'adr'\r",
        "'checkAddressRange start end val' checks, whether the value 'val' is equal to the content at the addresses in range 'start' to 'end'\r",
        "'v' returns the number of zeros and ones\n\r"
}
Definition at line 41 of file CommandLineParser.h.
Referenced by showHelp().
len
uint16_t CommandLineParser::len private
Definition at line 36 of file CommandLineParser.h.
Referenced by executeCommand().
m_arguments
uint32_t CommandLineParser::m_arguments[3] private
Definition at line 34 of file CommandLineParser.h.
m_commandMode
Command CommandLineParser::m_commandMode = NOPE private
Definition at line 33 of file CommandLineParser.h.
m_InterfaceWrapper
InterfaceWrapper* CommandLineParser::m_InterfaceWrapper private
Definition at line 48 of file CommandLineParser.h.
Referenced by CommandLineParser(), and executeCommand().
m_MemoryController
MemoryController* CommandLineParser::m_MemoryController private
Definition at line 44 of file CommandLineParser.h.
Referenced by executeCommand().
m_SendBuffer
char CommandLineParser::m_SendBuffer[STRING_BUFFER_SIZE] private
Definition at line 46 of file CommandLineParser.h.
Referenced by executeCommand().
m_WriteMode
uint8_t CommandLineParser::m_WriteMode = 0xFF private
Definition at line 35 of file CommandLineParser.h.
Referenced by executeCommand().
old_len
uint16_t CommandLineParser::old_len private
Definition at line 37 of file CommandLineParser.h.
Rx_Buffer
char CommandLineParser::Rx_Buffer[100] private
Definition at line 38 of file CommandLineParser.h.
The documentation for this class was generated from the following files:
/home/florianfrank/Documents/Research/Projects/PUFMem/stm_measurement_firmware/Inc/cpp/CommandLineParser.h
/home/florianfrank/Documents/Research/Projects/PUFMem/stm_measurement_firmware/Src/cpp/CommandLineParser.cpp