Memory Measurement Library (CPP): SPIWrapper Class Reference
SPIWrapper Class Reference
This class serves as wrapper for SPI communication. Currently this wrapper only supports an STM32F429DISC1 board.
#include <SPIWrapper.h>
Public Member Functions
SPIWrapper (const char *interfaceName, Mode spiMode=SPI_MASTER, BaudratePrescaler prescaler=SPI_Prescaler_2, ClockPhase clockPhase=SPIWrapper_CP_1_EDGE, ClockPoloarity clockPolarity=SPIWrapper_CPOL_LOW)
~SPIWrapper () override
MEM_ERROR Initialize () override
Here the mandatory functions to enable the interface must be executed. Like setting required clocks and ports.
MEM_ERROR SendData (uint8_t *data, uint16_t *size, uint32_t timeoutInMs) override
Send data on the specified SPI interface. CS must be set manually!
MEM_ERROR ReceiveData (uint8_t *data, uint16_t *size, uint32_t timeoutInMs) override
Receives data on the specified SPI interface. CS must be set manually!
Public Member Functions inherited from InterfaceWrapper
virtual ~InterfaceWrapper ()=default
virtual MEM_ERROR Initialize ()=0
Here the mandatory functions to enable the interface must be executed. Like setting required clocks and ports.
virtual MEM_ERROR SendData (uint8_t *data, uint16_t *size, uint32_t timeout)=0
This function must be implement to send data to the interface.
virtual MEM_ERROR ReceiveData (uint8_t *data, uint16_t *size, uint32_t timeout)=0
This function must be implement to receive data from the interface.
Static Public Member Functions
static void SetWriteProtect ()
Sets the Write Protect Pin on pin PC6.
static void ResetWriteProtect ()
Resets the Write Protect Pin. On the STM32 on pin PC6.
static void SetChipSelect ()
Sets the Chip Select Pin. On STM32 on pin PF6.
static void ResetChipSelect ()
Resets the Chip Select Pin. On STM32 on pin PF6.
static bool ReadChipSelect ()
This function reads the Chip Select signal if the the interface is used in slave mode.
Private Member Functions
MEM_ERROR InitializeSPIInterface (SPIHandle *spiProperties)
Private Attributes
SPIHandle * m_SPIHandle {}
DeviceWrapper * m_DeviceWrapper
std::vector< AvailableSPIProperties > m_AvailableSPIPorts
Detailed Description
This class serves as wrapper for SPI communication. Currently this wrapper only supports an STM32F429DISC1 board.
Definition at line 24 of file SPIWrapper.h.
Constructor & Destructor Documentation
SPIWrapper()
SPIWrapper::SPIWrapper (const char * interfaceName, Mode spiMode = SPI_MASTER, BaudratePrescaler prescaler = SPI_Prescaler_2, ClockPhase clockPhase = SPIWrapper_CP_1_EDGE, ClockPoloarity clockPolarity = SPIWrapper_CPOL_LOW) explicit
Author
Florian Frank
Copyright
University of Passau - Chair of computer engineering
Definition at line 22 of file SPIWrapper.cpp.
{
    m_SPIHandle = static_cast<SPIHandle *>(malloc(sizeof(SPIHandle)));
    m_SPIHandle->m_Prescaler = prescaler;
    m_SPIHandle->m_ClockPhase = clockPhase;
    m_SPIHandle->m_ClockPolarity = clockPolarity;
    m_SPIHandle->m_Mode = spiMode;
#if STM32
    m_DeviceWrapper = new STM32F429Wrapper();
    m_AvailableSPIPorts = {
            {SPI1, "SPI1", {IO_BANK_B,         IO_PIN_4},         {IO_BANK_UNDEFINED, IO_PIN_UNDEFINED}, {IO_BANK_A,         IO_PIN_5},         {IO_BANK_UNDEFINED, IO_PIN_UNDEFINED}},
            {SPI2, "SPI2", {IO_BANK_UNDEFINED, IO_PIN_UNDEFINED}, {IO_BANK_UNDEFINED, IO_PIN_UNDEFINED}, {IO_BANK_UNDEFINED, IO_PIN_UNDEFINED}, {IO_BANK_UNDEFINED, IO_PIN_UNDEFINED}},
            {SPI3, "SPI3", {IO_BANK_UNDEFINED, IO_PIN_UNDEFINED}, {IO_BANK_UNDEFINED, IO_PIN_UNDEFINED}, {IO_BANK_UNDEFINED, IO_PIN_UNDEFINED}, {IO_BANK_UNDEFINED, IO_PIN_UNDEFINED}},
            {SPI4, "SPI4", {IO_BANK_E,         IO_PIN_5},         {IO_BANK_E,         IO_PIN_6},         {IO_BANK_E,         IO_PIN_2},         {IO_BANK_E,         IO_PIN_4}},
            {SPI5, "SPI5", {IO_BANK_F,         IO_PIN_8},         {IO_BANK_F,         IO_PIN_9},         {IO_BANK_F,         IO_PIN_7},         {IO_BANK_F,         IO_PIN_6}},
            {SPI6, "SPI6", {IO_BANK_UNDEFINED, IO_PIN_UNDEFINED}, {IO_BANK_UNDEFINED, IO_PIN_UNDEFINED}, {IO_BANK_UNDEFINED, IO_PIN_UNDEFINED}, {IO_BANK_UNDEFINED, IO_PIN_UNDEFINED}},
            };
#else
    m_DeviceWrapper = new DeviceWrapper();
#endif
}
References IO_BANK_A, IO_BANK_B, IO_BANK_E, IO_BANK_F, IO_BANK_UNDEFINED, IO_PIN_2, IO_PIN_4, IO_PIN_5, IO_PIN_6, IO_PIN_7, IO_PIN_8, IO_PIN_9, IO_PIN_UNDEFINED, m_AvailableSPIPorts, SPIProperties::SPIHandle::m_ClockPhase, SPIProperties::SPIHandle::m_ClockPolarity, m_DeviceWrapper, SPIProperties::SPIHandle::m_Mode, SPIProperties::SPIHandle::m_Prescaler, and m_SPIHandle.
~SPIWrapper()
SPIWrapper::~SPIWrapper () override
Definition at line 47 of file SPIWrapper.cpp.
{
    delete m_SPIHandle;
    delete m_DeviceWrapper;
}
References m_DeviceWrapper, and m_SPIHandle.
Member Function Documentation
Initialize()
MEM_ERROR SPIWrapper::Initialize () override virtual
Here the mandatory functions to enable the interface must be executed. Like setting required clocks and ports.
Returns
MEM_ERROR if no error occured otherwise return an error code.
Implements InterfaceWrapper.
Definition at line 54 of file SPIWrapper.cpp.
{
    return InitializeSPIInterface(m_SPIHandle);
}
References InitializeSPIInterface(), and m_SPIHandle.
InitializeSPIInterface()
MEM_ERROR SPIWrapper::InitializeSPIInterface (SPIHandle * spiProperties) private
Definition at line 114 of file SPIWrapper.cpp.
{
    m_SPIHandle = spiProperties;
    return MemoryErrorHandling::MEM_NO_ERROR;
}
References m_SPIHandle, and MemoryErrorHandling::MEM_NO_ERROR.
Referenced by Initialize().
ReadChipSelect()
bool SPIWrapper::ReadChipSelect () inline static
This function reads the Chip Select signal if the the interface is used in slave mode.
Returns
Returns the value of the GPIO pin.
Definition at line 259 of file SPIWrapper.cpp.
{
#if STM32
    return  HAL_GPIO_ReadPin(SPI5_CS_GPIO_Port, SPI5_CS_Pin) == GPIO_PIN_RESET;
#endif // STM32
    return false; // TODO
}
Referenced by ReceiveData(), and SendData().
ReceiveData()
MEM_ERROR SPIWrapper::ReceiveData (uint8_t * data, uint16_t * size, uint32_t timeoutInMs) override virtual
Receives data on the specified SPI interface. CS must be set manually!
Parameters
data byte buffer which is returned.
size the input specifies the maximum size of the read buffer. The same buffer is used to set the output size.
timeoutInMs timeoutInMs in ms when using blocking functions.
Returns
MEM_NO_ERROR if execution was successful.
Implements InterfaceWrapper.
Definition at line 214 of file SPIWrapper.cpp.
{
    if(!size || *size == 0)
        return MemoryErrorHandling::MEM_INVALID_ARGUMENT;
    bool retCS = ReadChipSelect();
    TimeMeasurement tm{};
    uint32_t timeStampStart = tm.ResetAndStartTimer();
    while(!retCS && tm.GetElapsedTimeInMS() - timeStampStart < timeoutInMs)
    {
        retCS = ReadChipSelect();
    }
    MEM_ERROR ret;
    if(m_SPIHandle->m_Mode == SPI_MASTER)
        SetChipSelect();
    else
    {
        bool readEnable = false;
        TimeMeasurement tm;
        uint32_t timeStampStart = tm.ResetAndStartTimer();
        while(!readEnable)
        {
            readEnable = ReadChipSelect();
            if(tm.GetElapsedTimeInMS() >= timeoutInMs)
                return MemoryErrorHandling::MEM_HAL_TIMEOUT;
        }
    }
#if STM32
        ret = MemoryErrorHandling::HAL_StatusTypeDefToErr(HAL_SPI_Receive(&m_SPIHandle->m_SPIHandle, data, *size, timeoutInMs));
#else
    //m_SPIHandle.ReadBuffer(data, size); TODO
    ret = MemoryErrorHandling::MEM_NO_ERROR;
#endif // STM32
    if(m_SPIHandle->m_Mode == SPI_MASTER)
        ResetChipSelect();
    return ret;
}
References TimeMeasurement::GetElapsedTimeInMS(), MemoryErrorHandling::HAL_StatusTypeDefToErr(), SPIProperties::SPIHandle::m_Mode, SPIProperties::SPIHandle::m_SPIHandle, m_SPIHandle, MemoryErrorHandling::MEM_HAL_TIMEOUT, MemoryErrorHandling::MEM_INVALID_ARGUMENT, MemoryErrorHandling::MEM_NO_ERROR, ReadChipSelect(), TimeMeasurement::ResetAndStartTimer(), ResetChipSelect(), SetChipSelect(), and SPIProperties::SPI_MASTER.
Referenced by MemoryControllerSPI::Read8BitWord(), and MemoryControllerSPI::SendSPICommand().
ResetChipSelect()
void SPIWrapper::ResetChipSelect () inline static
Resets the Chip Select Pin. On STM32 on pin PF6.
Definition at line 153 of file SPIWrapper.cpp.
{
#if STM32
    HAL_GPIO_WritePin(SPI5_CS_GPIO_Port, SPI5_CS_Pin, GPIO_PIN_SET);
#endif // STM32
}
Referenced by ReceiveData(), and SendData().
ResetWriteProtect()
void SPIWrapper::ResetWriteProtect () static
Resets the Write Protect Pin. On the STM32 on pin PC6.
Definition at line 133 of file SPIWrapper.cpp.
{
#if STM32
    HAL_GPIO_WritePin(SPI5_WP_GPIO_Port, SPI5_WP_Pin, GPIO_PIN_SET);
#endif // STM32
}
Referenced by MemoryControllerSPI::Read8BitWord(), MemoryControllerSPI::Reset_WriteEnableLatch(), MemoryControllerSPI::SetWriteEnableLatch(), and MemoryControllerSPI::Write8BitWord().
SendData()
MEM_ERROR SPIWrapper::SendData (uint8_t * data, uint16_t * size, uint32_t timeoutInMs) override virtual
Send data on the specified SPI interface. CS must be set manually!
Parameters
data byte buffer to send.
size input size to send.
timeoutInMs timeoutInMs when using blocking SPI functions.
Returns
MEM_NO_ERROR if execution was successful.
Implements InterfaceWrapper.
Definition at line 167 of file SPIWrapper.cpp.
{
    if(!size || *size == 0)
        return MemoryErrorHandling::MEM_INVALID_ARGUMENT;
    bool retCS = ReadChipSelect();
    TimeMeasurement tm{};
    tm.ResetAndStartTimer();
    while(!retCS)
    {
        if(tm.GetElapsedTimeInMS())
            return MemoryErrorHandling::MEM_HAL_TIMEOUT;
        retCS = ReadChipSelect();
    }
    bool writeEnable = false;
    MEM_ERROR ret;
    if(m_SPIHandle->m_Mode == SPI_MASTER)
        SetChipSelect();
    else
    {
        while(!writeEnable)
        {
            writeEnable = ReadChipSelect();
            if(tm.GetElapsedTimeInMS() >= timeoutInMs)
                return MemoryErrorHandling::MEM_HAL_TIMEOUT;
        }
    }
#if STM32
        ret = MemoryErrorHandling::HAL_StatusTypeDefToErr(
                HAL_SPI_Transmit(&m_SPIHandle->m_SPIHandle, data, *size, timeoutInMs));
#else
  //  m_SPIHandle.StoreBuffer(data, size); TODO
#endif // STM32
    if(m_SPIHandle->m_Mode == SPI_MASTER)
        ResetChipSelect();
    return ret;
}
References MemoryErrorHandling::HAL_StatusTypeDefToErr(), SPIProperties::SPIHandle::m_Mode, SPIProperties::SPIHandle::m_SPIHandle, m_SPIHandle, MemoryErrorHandling::MEM_HAL_TIMEOUT, MemoryErrorHandling::MEM_INVALID_ARGUMENT, ReadChipSelect(), TimeMeasurement::ResetAndStartTimer(), ResetChipSelect(), SetChipSelect(), and SPIProperties::SPI_MASTER.
Referenced by MemoryControllerSPI::Read8BitWord(), MemoryControllerSPI::SendSPICommand(), and MemoryControllerSPI::Write8BitWord().
SetChipSelect()
void SPIWrapper::SetChipSelect () static
Sets the Chip Select Pin. On STM32 on pin PF6.
Definition at line 143 of file SPIWrapper.cpp.
{
#if STM32
    HAL_GPIO_WritePin(SPI5_CS_GPIO_Port, SPI5_CS_Pin, GPIO_PIN_RESET);
#endif // STM32
}
Referenced by ReceiveData(), and SendData().
SetWriteProtect()
void SPIWrapper::SetWriteProtect () static
Sets the Write Protect Pin on pin PC6.
Definition at line 123 of file SPIWrapper.cpp.
{
#if STM32
    HAL_GPIO_WritePin(SPI5_WP_GPIO_Port, SPI5_WP_Pin, GPIO_PIN_RESET);
#endif // STM32
}
Referenced by MemoryControllerSPI::Read8BitWord(), MemoryControllerSPI::Reset_WriteEnableLatch(), MemoryControllerSPI::SetWriteEnableLatch(), and MemoryControllerSPI::Write8BitWord().
Field Documentation
m_AvailableSPIPorts
std::vector<AvailableSPIProperties> SPIWrapper::m_AvailableSPIPorts private
Definition at line 57 of file SPIWrapper.h.
Referenced by SPIWrapper().
m_DeviceWrapper
DeviceWrapper* SPIWrapper::m_DeviceWrapper private
Definition at line 56 of file SPIWrapper.h.
Referenced by SPIWrapper(), and ~SPIWrapper().
m_SPIHandle
SPIHandle* SPIWrapper::m_SPIHandle {} private
Definition at line 52 of file SPIWrapper.h.
Referenced by Initialize(), InitializeSPIInterface(), ReceiveData(), SendData(), SPIWrapper(), and ~SPIWrapper().
The documentation for this class was generated from the following files:
/home/florianfrank/Documents/Research/Projects/PUFMem/stm_measurement_firmware/Inc/cpp/InterfaceWrappers/SPIWrapper.h
/home/florianfrank/Documents/Research/Projects/PUFMem/stm_measurement_firmware/Src/cpp/InterfaceWrappers/SPIWrapper.cpp