Memory Measurement Library (CPP): ReRAM_Fujitsu_MB85AS4MTPF_G_BCERE1 Class Reference
ReRAM_Fujitsu_MB85AS4MTPF_G_BCERE1 Class Reference
This class sets the parameters for an an RERAM Fujitsu MB85AS4MTPF memory chip. See link Memory Datasheet.
#include <ReRAM_Fujitsu_MB85AS4MTPF_G_BCERE1.h>
Public Member Functions
ReRAM_Fujitsu_MB85AS4MTPF_G_BCERE1 ()
~ReRAM_Fujitsu_MB85AS4MTPF_G_BCERE1 () override
MEM_ERROR Initialize () override
MEM_ERROR CreateWriteMessage (uint32_t address, uint8_t valueToWrite, uint8_t *returnSendBuffer, uint16_t *sendBufferSize) override
Creates the byte buffer containing the command to write from an Fujitsu MB85AS4M ReRAM chip. The read frame has following format <0x02, third address byte, second address byte, first address byte, valueToWrite to send>
MEM_ERROR CreateReadMessage (uint32_t address, uint8_t *sendBuffer, uint16_t *sendBufferSize) override
Creates the byte buffer containing the command to read from an Fujitsu MB85AS4M ReRAM chip. The read frame has following format <0x03, third address byte, second address byte, first address byte>
Public Member Functions inherited from MemoryModule
MemoryModule ()=delete
virtual MEM_ERROR Initialize ()
virtual MEM_ERROR CreateWriteMessage (uint32_t address, uint8_t valueToWrite, uint8_t *returnSendBuffer, uint16_t *sendBufferSize)
virtual MEM_ERROR CreateReadMessage (uint32_t address, uint8_t *sendBuffer, uint16_t *sendBufferSize)
Type GetMemoryType () const
const std::string & GetMemoryLabel () const
Connection GetConnectionType () const
uint8_t GetBitWidth () const
uint32_t GetMemorySize () const
const TemperatureProperties & GetTemperatureProperties () const
const VoltageProperties & GetVoltageProperties () const
Private Attributes
SPIWrapper * m_SPIWrapper
Additional Inherited Members
Protected Member Functions inherited from MemoryModule
MemoryModule (Type memoryType, const char *memoryLabel, Connection connectionType, uint8_t bitWidth, uint32_t memorySize, TemperatureProperties temperatureProperties, VoltageProperties voltageProperties)
virtual ~MemoryModule ()
MEM_ERROR Initialize (InterfaceWrapper *interfaceWrapper)
Protected Attributes inherited from MemoryModule
Type m_MemoryType
std::string m_MemoryLabel
Connection m_ConnectionType
uint8_t m_BitWidth
uint32_t m_MemorySize
TemperatureProperties m_TemperatureProperties
VoltageProperties m_VoltageProperties
Detailed Description
This class sets the parameters for an an RERAM Fujitsu MB85AS4MTPF memory chip. See link Memory Datasheet.
Definition at line 15 of file ReRAM_Fujitsu_MB85AS4MTPF_G_BCERE1.h.
Constructor & Destructor Documentation
ReRAM_Fujitsu_MB85AS4MTPF_G_BCERE1()
ReRAM_Fujitsu_MB85AS4MTPF_G_BCERE1::ReRAM_Fujitsu_MB85AS4MTPF_G_BCERE1 ()
Author
Florian Frank
Copyright
University of Passau - Chair of Computer Engineering
Definition at line 10 of file ReRAM_Fujitsu_MB85AS4MTPF_G_BCERE1.cpp.
                                                                      : MemoryModule(MemoryProperties::TYPE_RERAM,
                                                                                       "ReRAM_Fujitsu_MB85AS4MTPF_G_BCERE1",
                                                                                       MemoryProperties::SPI, 8, 524288, {233, 358},
                                                                                       {3000, 3600})
{
    m_SPIWrapper = new SPIWrapper("SPI5");
}
~ReRAM_Fujitsu_MB85AS4MTPF_G_BCERE1()
ReRAM_Fujitsu_MB85AS4MTPF_G_BCERE1::~ReRAM_Fujitsu_MB85AS4MTPF_G_BCERE1 () override
Definition at line 18 of file ReRAM_Fujitsu_MB85AS4MTPF_G_BCERE1.cpp.
{
    delete m_SPIWrapper;
}
References m_SPIWrapper.
Member Function Documentation
CreateReadMessage()
MEM_ERROR ReRAM_Fujitsu_MB85AS4MTPF_G_BCERE1::CreateReadMessage (uint32_t address, uint8_t * sendBuffer, uint16_t * sendBufferSize) override virtual
Creates the byte buffer containing the command to read from an Fujitsu MB85AS4M ReRAM chip. The read frame has following format <0x03, third address byte, second address byte, first address byte>
Parameters
address the address is subdivided into the first, second and third byte and copied into the sendBuffer.
sendBuffer the buffer containing the commands to send over the SPI interface.
sendBufferSize the size of the command buffer. To indicate how many bytes should be sent.
Returns
MEM_NO_ERROR if no error occurred otherwise return error code.
Reimplemented from MemoryModule.
Definition at line 65 of file ReRAM_Fujitsu_MB85AS4MTPF_G_BCERE1.cpp.
{
    if (MemoryController::IsInvalidAddress(address, m_MemorySize))
        return MemoryErrorHandling::MEM_INVALID_ADDRESS;
    if (!sendBufferSize || *sendBufferSize < 4)
        return MemoryErrorHandling::MEM_BUFFER_TO_SMALL;
    uint8_t initialize_write_data[] = {MemoryControllerSPI::ReRAM_READ, static_cast<uint8_t>(((address >> 16) & 0xFF)),
                                       static_cast<uint8_t>(((address >> 8) & 0xFF)),
                                       static_cast<uint8_t>(((address >> 0) & 0xFF))};
    memcpy(sendBuffer, initialize_write_data, sizeof initialize_write_data);
    *sendBufferSize = 4;
    return MemoryErrorHandling::MEM_NO_ERROR;
}
References MemoryController::IsInvalidAddress(), MemoryModule::m_MemorySize, MemoryErrorHandling::MEM_BUFFER_TO_SMALL, MemoryErrorHandling::MEM_INVALID_ADDRESS, MemoryErrorHandling::MEM_NO_ERROR, and MemoryControllerSPI::ReRAM_READ.
CreateWriteMessage()
MEM_ERROR ReRAM_Fujitsu_MB85AS4MTPF_G_BCERE1::CreateWriteMessage (uint32_t address, uint8_t valueToWrite, uint8_t * returnSendBuffer, uint16_t * sendBufferSize) override virtual
Creates the byte buffer containing the command to write from an Fujitsu MB85AS4M ReRAM chip. The read frame has following format <0x02, third address byte, second address byte, first address byte, valueToWrite to send>
Parameters
address the address is subdivided into the first, second and third byte and copied into the sendBuffer.
valueToWrite the value which should be written on the address.
sendBuffer the buffer containing the commands to send over the SPI interface.
sendBufferSize the size of the command buffer. To indicate how many bytes should be sent.
Returns
MEM_NO_ERROR if no error occurred otherwise return error code.
Reimplemented from MemoryModule.
Definition at line 37 of file ReRAM_Fujitsu_MB85AS4MTPF_G_BCERE1.cpp.
{
    if (MemoryController::IsInvalidAddress(address, m_MemorySize))
        return MemoryErrorHandling::MEM_INVALID_ADDRESS;
    if (!sendBufferSize || *sendBufferSize < 5)
        return MemoryErrorHandling::MEM_BUFFER_TO_SMALL;
    uint8_t initialize_write_data[] = {MemoryControllerSPI::ReRAM_WRITE, static_cast<uint8_t>(((address >> 16) & 0xFF)),
                                       static_cast<uint8_t>(((address >> 8) & 0xFF)),
                                       static_cast<uint8_t>(((address >>  0) & 0xFF)), valueToWrite};
    memcpy(returnSendBuffer, initialize_write_data, sizeof initialize_write_data);
    *sendBufferSize = 5;
    return MemoryErrorHandling::MEM_NO_ERROR;
}
References MemoryController::IsInvalidAddress(), MemoryModule::m_MemorySize, MemoryErrorHandling::MEM_BUFFER_TO_SMALL, MemoryErrorHandling::MEM_INVALID_ADDRESS, MemoryErrorHandling::MEM_NO_ERROR, and MemoryControllerSPI::ReRAM_WRITE.
Initialize()
MEM_ERROR ReRAM_Fujitsu_MB85AS4MTPF_G_BCERE1::Initialize () override virtual
Reimplemented from MemoryModule.
Definition at line 23 of file ReRAM_Fujitsu_MB85AS4MTPF_G_BCERE1.cpp.
{
    return MemoryModule::Initialize(m_SPIWrapper);
}
References MemoryModule::Initialize(), and m_SPIWrapper.
Field Documentation
m_SPIWrapper
SPIWrapper* ReRAM_Fujitsu_MB85AS4MTPF_G_BCERE1::m_SPIWrapper private
Definition at line 27 of file ReRAM_Fujitsu_MB85AS4MTPF_G_BCERE1.h.
Referenced by Initialize(), and ~ReRAM_Fujitsu_MB85AS4MTPF_G_BCERE1().
The documentation for this class was generated from the following files:
/home/florianfrank/Documents/Research/Projects/PUFMem/stm_measurement_firmware/Inc/cpp/MemoryModules/ReRAM_Fujitsu_MB85AS4MTPF_G_BCERE1.h
/home/florianfrank/Documents/Research/Projects/PUFMem/stm_measurement_firmware/Src/cpp/MemoryModules/ReRAM_Fujitsu_MB85AS4MTPF_G_BCERE1.cpp