Memory Measurement Library (CPP): /home/florianfrank/Documents/Research/Projects/PUFMem/stm_measurement_firmware/Inc/cpp/Main/Main.h File Reference
Main.h File Reference
Functions
int main ()
The application entry point.
Function Documentation
main()
int main ()
The application entry point.
Author
Florian Frank
Copyright
University of Passau - Chair of computer engineering
Return values
int
Definition at line 27 of file Main.cpp.
{
#if STM32
    STM32F429Wrapper device;
    device.Initialize();
#endif
    RERAM_ADESTO_RM25C512C_LTAI_T fram;
    MemoryControllerParallel memoryController(nullptr, fram);
    memoryController.Initialize();
/*    for (uint32_t i = 0; i < fram.GetMemorySize(); i++)
    {
        memoryController.Write8BitWord(i, 0xFF);
        HAL_Delay(10);
    }*/
    uint8_t retValue = 0x00;
    for (uint32_t i = 0; i < fram.GetMemorySize(); i++)
    {
        memoryController.Read8BitWord(i, &retValue);
    }
    /* USER CODE END 3 */
}
References MemoryModule::GetMemorySize(), MemoryControllerParallel::Initialize(), and MemoryControllerParallel::Read8BitWord().