Memory Measurement Library (CPP): TimeMeasurement Class Reference
TimeMeasurement Class Reference
This class provides functions to measure the elapsed time using Cortex M4 registers.
#include <TimeMeasurement.h>
Public Member Functions
uint32_t ResetAndStartTimer ()
Resets the previous timer by resetting the counter and restarts the measurements by setting the CYCCNT register.
uint32_t GetClockCycles ()
Resets the counter used to count the clock cycles.
uint32_t GetElapsedTimeInNS ()
Returns the elapsed time since calling StartTimer() in nanoseconds.
uint32_t GetElapsedTimeInMS ()
void ResetTimer ()
Resets the counter used to count the clock cycles.
uint32_t StopTimer ()
uint32_t GetTimer () const
Returns the current timer value.
Static Public Member Functions
static uint32_t TransformClockFrequencyToNs (uint32_t value)
Transforms the clock counts based on the frequency to nano seconds.
static uint32_t TransformClockFrequencyToMs (uint32_t value)
Private Attributes
unsigned long long m_StartTimer
unsigned long long m_StopTimer
Detailed Description
This class provides functions to measure the elapsed time using Cortex M4 registers.
Author
Florian Frank
Copyright
University of Passau - Chair of computer engineering
Definition at line 13 of file TimeMeasurement.h.
Member Function Documentation
GetClockCycles()
uint32_t TimeMeasurement::GetClockCycles ()
Resets the counter used to count the clock cycles.
Definition at line 81 of file TimeMeasurement.cpp.
{
#if STM32
    uint32_t ret = GetTimer();
    ResetTimer();
    return ret;
#else
    return 0; // TODO not implemented yet
#endif
}
References GetTimer(), and ResetTimer().
GetElapsedTimeInMS()
uint32_t TimeMeasurement::GetElapsedTimeInMS ()
Definition at line 101 of file TimeMeasurement.cpp.
{
    return TransformClockFrequencyToMs(GetTimer());
}
References GetTimer(), and TransformClockFrequencyToMs().
Referenced by SPIWrapper::ReceiveData().
GetElapsedTimeInNS()
uint32_t TimeMeasurement::GetElapsedTimeInNS ()
Returns the elapsed time since calling StartTimer() in nanoseconds.
Returns
elapsed time in ns.
Definition at line 96 of file TimeMeasurement.cpp.
{
    return TransformClockFrequencyToNs(GetTimer());
}
References GetTimer(), and TransformClockFrequencyToNs().
GetTimer()
uint32_t TimeMeasurement::GetTimer () const
Returns the current timer value.
Returns
Timer value.
Definition at line 55 of file TimeMeasurement.cpp.
{
    if(m_StopTimer != 0)
        return m_StopTimer - m_StartTimer;
    else
        return std::chrono::system_clock::now().time_since_epoch().count() - m_StartTimer;
}
References m_StartTimer, and m_StopTimer.
Referenced by GetClockCycles(), GetElapsedTimeInMS(), and GetElapsedTimeInNS().
ResetAndStartTimer()
uint32_t TimeMeasurement::ResetAndStartTimer ()
Resets the previous timer by resetting the counter and restarts the measurements by setting the CYCCNT register.
Returns
start timer value TODO is this really necessary?
Definition at line 23 of file TimeMeasurement.cpp.
{
#if __linux__
    ResetTimer();
    return m_StartTimer;
#else
#if STM32
    ResetTimer();
    start_timer();
    return get_timer();
#endif // STM32
#endif // if __linux__
}
References get_timer, m_StartTimer, ResetTimer(), and start_timer.
Referenced by MemoryControllerSPI::PollWriteInProgressRegister(), SPIWrapper::ReceiveData(), and SPIWrapper::SendData().
ResetTimer()
void TimeMeasurement::ResetTimer ()
Resets the counter used to count the clock cycles.
Definition at line 66 of file TimeMeasurement.cpp.
{
#if __linux__
    auto ret = std::chrono::system_clock::now();
    m_StartTimer = ret.time_since_epoch().count();
#else // not linux
    #if STM32
        reset_timer();
    #endif // STM32
#endif // if __linux__
}
References m_StartTimer, and reset_timer.
Referenced by GetClockCycles(), and ResetAndStartTimer().
StopTimer()
uint32_t TimeMeasurement::StopTimer ()
Definition at line 38 of file TimeMeasurement.cpp.
{
#if __linux__
    auto ret = std::chrono::system_clock::now();
    m_StopTimer = ret.time_since_epoch().count();
#else // not __linux__
#if STM32
    stop_timer();
#endif // STM32
#endif // if __linux__
    return m_StopTimer;
}
References m_StopTimer, and stop_timer.
TransformClockFrequencyToMs()
uint32_t TimeMeasurement::TransformClockFrequencyToMs (uint32_t value) static
Definition at line 122 of file TimeMeasurement.cpp.
{
#if __linux__
    return value;
#else // not __linux__
    #if STM32
        return static_cast<uint32_t>((float)value * 1/CLOCK_FREQUENCY);
    #endif
#endif // if __linux__
}
References CLOCK_FREQUENCY.
Referenced by GetElapsedTimeInMS(), and MemoryControllerSPI::SetWriteEnableLatch().
TransformClockFrequencyToNs()
uint32_t TimeMeasurement::TransformClockFrequencyToNs (uint32_t value) static
Transforms the clock counts based on the frequency to nano seconds.
Parameters
value clock count value.
Returns
elapsed time in ns.
Definition at line 111 of file TimeMeasurement.cpp.
{
#if __linux__
    return value; // TODO CHECK
#else // not __linux__
    #if STM32
        return static_cast<uint32_t>((float)value * 1/CLOCK_FREQUENCY);
    #endif
#endif // if __linux__
}
References CLOCK_FREQUENCY.
Referenced by GetElapsedTimeInNS().
Field Documentation
m_StartTimer
unsigned long long TimeMeasurement::m_StartTimer private
Definition at line 34 of file TimeMeasurement.h.
Referenced by GetTimer(), ResetAndStartTimer(), and ResetTimer().
m_StopTimer
unsigned long long TimeMeasurement::m_StopTimer private
Definition at line 35 of file TimeMeasurement.h.
Referenced by GetTimer(), and StopTimer().
The documentation for this class was generated from the following files:
/home/florianfrank/Documents/Research/Projects/PUFMem/stm_measurement_firmware/Inc/cpp/TimeMeasurement.h
/home/florianfrank/Documents/Research/Projects/PUFMem/stm_measurement_firmware/Src/cpp/TimeMeasurement.cpp