Memory Measurement Library (CPP): MemoryModule Class Reference
MemoryModule Class Reference
This abstract class provides all the required functions to be implemented by a new memory module.
#include <MemoryModule.h>
Public Member Functions
MemoryModule ()=delete
virtual MEM_ERROR Initialize ()
virtual MEM_ERROR CreateWriteMessage (uint32_t address, uint8_t valueToWrite, uint8_t *returnSendBuffer, uint16_t *sendBufferSize)
virtual MEM_ERROR CreateReadMessage (uint32_t address, uint8_t *sendBuffer, uint16_t *sendBufferSize)
Type GetMemoryType () const
const std::string & GetMemoryLabel () const
Connection GetConnectionType () const
uint8_t GetBitWidth () const
uint32_t GetMemorySize () const
const TemperatureProperties & GetTemperatureProperties () const
const VoltageProperties & GetVoltageProperties () const
Protected Member Functions
MemoryModule (Type memoryType, const char *memoryLabel, Connection connectionType, uint8_t bitWidth, uint32_t memorySize, TemperatureProperties temperatureProperties, VoltageProperties voltageProperties)
virtual ~MemoryModule ()
MEM_ERROR Initialize (InterfaceWrapper *interfaceWrapper)
Protected Attributes
Type m_MemoryType
std::string m_MemoryLabel
Connection m_ConnectionType
uint8_t m_BitWidth
uint32_t m_MemorySize
TemperatureProperties m_TemperatureProperties
VoltageProperties m_VoltageProperties
Detailed Description
This abstract class provides all the required functions to be implemented by a new memory module.
Definition at line 21 of file MemoryModule.h.
Constructor & Destructor Documentation
MemoryModule() [1/2]
MemoryModule::MemoryModule () delete
MemoryModule() [2/2]
MemoryModule::MemoryModule (Type memoryType, const char * memoryLabel, Connection connectionType, uint8_t bitWidth, uint32_t memorySize, TemperatureProperties temperatureProperties, VoltageProperties voltageProperties) protected
Author
Florian Frank
Copyright
University of Passau - Chair of Computer Engineering
Definition at line 9 of file MemoryModule.cpp.
                                                                : m_MemoryType(memoryType),
                                                                    m_MemoryLabel(memoryLabel),
                                                                    m_ConnectionType(connectionType),
                                                                    m_BitWidth(bitWidth), m_MemorySize(memorySize),
                                                                    m_TemperatureProperties(temperatureProperties),
                                                                    m_VoltageProperties(voltageProperties)
{}
~MemoryModule()
MemoryModule::~MemoryModule () protected virtual
Definition at line 20 of file MemoryModule.cpp.
{
}
Member Function Documentation
CreateReadMessage()
MEM_ERROR MemoryModule::CreateReadMessage (uint32_t address, uint8_t * sendBuffer, uint16_t * sendBufferSize) virtual
Reimplemented in RERAM_ADESTO_RM25C512C_LTAI_T, and ReRAM_Fujitsu_MB85AS4MTPF_G_BCERE1.
Definition at line 76 of file MemoryModule.cpp.
{
    return MemoryErrorHandling::MEM_MEMORY_NOT_SUPPORTED; // TODO parallele speicher
}
References MemoryErrorHandling::MEM_MEMORY_NOT_SUPPORTED.
Referenced by MemoryControllerSPI::Read8BitWord().
CreateWriteMessage()
MEM_ERROR MemoryModule::CreateWriteMessage (uint32_t address, uint8_t valueToWrite, uint8_t * returnSendBuffer, uint16_t * sendBufferSize) virtual
Reimplemented in RERAM_ADESTO_RM25C512C_LTAI_T, and ReRAM_Fujitsu_MB85AS4MTPF_G_BCERE1.
Definition at line 70 of file MemoryModule.cpp.
{
    return MemoryErrorHandling::MEM_MEMORY_NOT_SUPPORTED; // TODO parallele speicher
}
References MemoryErrorHandling::MEM_MEMORY_NOT_SUPPORTED.
Referenced by MemoryControllerSPI::Write8BitWord().
GetBitWidth()
uint8_t MemoryModule::GetBitWidth () const
Definition at line 44 of file MemoryModule.cpp.
{
    return m_BitWidth;
}
References m_BitWidth.
Referenced by MemoryController::FillMemoryWithAlternatingOneAndZero(), MemoryController::FillMemoryWithAlternatingZeroAndOne(), MemoryController::FillMemoryWithAscendingValues(), MemoryController::FillMemoryWithAscendingValuesAndVerifyRead(), MemoryController::FillWithOnes(), MemoryController::FillWithZeros(), MemoryController::FillWithZerosAndVerifyRead(), MemoryControllerSPI::Read16BitWord(), and MemoryControllerSPI::Write16BitWord().
GetConnectionType()
Connection MemoryModule::GetConnectionType () const
Definition at line 39 of file MemoryModule.cpp.
{
    return m_ConnectionType;
}
References m_ConnectionType.
Referenced by MemoryControllerSPI::MemoryControllerSPI().
GetMemoryLabel()
const std::string & MemoryModule::GetMemoryLabel () const
Definition at line 34 of file MemoryModule.cpp.
{
    return m_MemoryLabel;
}
References m_MemoryLabel.
GetMemorySize()
uint32_t MemoryModule::GetMemorySize () const
Definition at line 49 of file MemoryModule.cpp.
{
    return m_MemorySize;
}
References m_MemorySize.
Referenced by MemoryController::FillMemoryWithAlternatingOneAndZero(), MemoryController::FillMemoryWithAlternatingZeroAndOne(), MemoryController::FillMemoryWithAscendingValues(), MemoryController::FillMemoryWithAscendingValuesAndVerifyRead(), MemoryController::FillWithOnes(), MemoryController::FillWithZeros(), MemoryController::FillWithZerosAndVerifyRead(), main(), MemoryControllerParallel::Read8BitWord(), and MemoryControllerParallel::Write8BitWord().
GetMemoryType()
Type MemoryModule::GetMemoryType () const
Definition at line 29 of file MemoryModule.cpp.
{
    return m_MemoryType;
}
References m_MemoryType.
GetTemperatureProperties()
const TemperatureProperties & MemoryModule::GetTemperatureProperties () const
Definition at line 54 of file MemoryModule.cpp.
{
    return m_TemperatureProperties;
}
References m_TemperatureProperties.
GetVoltageProperties()
const VoltageProperties & MemoryModule::GetVoltageProperties () const
Definition at line 59 of file MemoryModule.cpp.
{
    return m_VoltageProperties;
}
References m_VoltageProperties.
Initialize() [1/2]
MEM_ERROR MemoryModule::Initialize () virtual
Reimplemented in FRAM_Cypress_FM22L16_55_TG, FRAM_Fujitsu_MB85R1001ANC_GE1, FRAM_Rohm_MR48V256CTAZAARL, MRAM_Everspin_MR4A08BUYS45, RERAM_ADESTO_RM25C512C_LTAI_T, ReRAM_Fujitsu_MB85AS4MTPF_G_BCERE1, SRAM_Alliance_AS7C34098A, SRAM_Alliance_AS7C38098A, SRAM_Cypress_CY7C1041CV33, SRAM_Cypress_CY7C1051CDV33, and SRAM_ISSI_IS61WV51216BLL.
Definition at line 65 of file MemoryModule.cpp.
{
    return MemoryErrorHandling::MEM_MEMORY_NOT_SUPPORTED;
}
References MemoryErrorHandling::MEM_MEMORY_NOT_SUPPORTED.
Referenced by FRAM_Cypress_FM22L16_55_TG::Initialize(), FRAM_Fujitsu_MB85R1001ANC_GE1::Initialize(), FRAM_Rohm_MR48V256CTAZAARL::Initialize(), MRAM_Everspin_MR4A08BUYS45::Initialize(), RERAM_ADESTO_RM25C512C_LTAI_T::Initialize(), ReRAM_Fujitsu_MB85AS4MTPF_G_BCERE1::Initialize(), SRAM_Alliance_AS7C34098A::Initialize(), SRAM_Alliance_AS7C38098A::Initialize(), SRAM_Cypress_CY7C1041CV33::Initialize(), SRAM_Cypress_CY7C1051CDV33::Initialize(), SRAM_ISSI_IS61WV51216BLL::Initialize(), and MemoryControllerSPI::MemoryControllerSPI().
Initialize() [2/2]
MEM_ERROR MemoryModule::Initialize (InterfaceWrapper * interfaceWrapper) protected
Definition at line 24 of file MemoryModule.cpp.
{
    return MemoryErrorHandling::MEM_NO_ERROR;
}
References MemoryErrorHandling::MEM_NO_ERROR.
Field Documentation
m_BitWidth
uint8_t MemoryModule::m_BitWidth protected
Definition at line 56 of file MemoryModule.h.
Referenced by GetBitWidth().
m_ConnectionType
Connection MemoryModule::m_ConnectionType protected
Definition at line 55 of file MemoryModule.h.
Referenced by GetConnectionType().
m_MemoryLabel
std::string MemoryModule::m_MemoryLabel protected
Definition at line 54 of file MemoryModule.h.
Referenced by GetMemoryLabel().
m_MemorySize
uint32_t MemoryModule::m_MemorySize protected
Definition at line 57 of file MemoryModule.h.
Referenced by RERAM_ADESTO_RM25C512C_LTAI_T::CreateReadMessage(), ReRAM_Fujitsu_MB85AS4MTPF_G_BCERE1::CreateReadMessage(), RERAM_ADESTO_RM25C512C_LTAI_T::CreateWriteMessage(), ReRAM_Fujitsu_MB85AS4MTPF_G_BCERE1::CreateWriteMessage(), and GetMemorySize().
m_MemoryType
Type MemoryModule::m_MemoryType protected
Definition at line 53 of file MemoryModule.h.
Referenced by GetMemoryType().
m_TemperatureProperties
TemperatureProperties MemoryModule::m_TemperatureProperties protected
Definition at line 58 of file MemoryModule.h.
Referenced by GetTemperatureProperties().
m_VoltageProperties
VoltageProperties MemoryModule::m_VoltageProperties protected
Definition at line 59 of file MemoryModule.h.
Referenced by GetVoltageProperties().
The documentation for this class was generated from the following files:
/home/florianfrank/Documents/Research/Projects/PUFMem/stm_measurement_firmware/Inc/cpp/MemoryModules/MemoryModule.h
/home/florianfrank/Documents/Research/Projects/PUFMem/stm_measurement_firmware/Src/cpp/MemoryModules/MemoryModule.cpp