Memory Measurement Library (CPP): MemoryController Class Reference
MemoryController Class Reference
#include <MemoryController.h>
Public Member Functions
MemoryController (InterfaceWrapper *interfaceWrapper, MemoryModule &memoryModule)
virtual ~MemoryController ()
virtual MEM_ERROR Initialize ()
virtual MEM_ERROR Write8BitWord (uint32_t adr, uint8_t value)
virtual MEM_ERROR Read8BitWord (uint32_t adr, uint8_t *ret)
virtual MEM_ERROR Write16BitWord (uint32_t adr, uint16_t value)
virtual MEM_ERROR Read16BitWord (uint32_t adr, uint16_t *value)
MEM_ERROR WriteSingleValue (uint32_t address, uint8_t value)
MEM_ERROR WriteSingleValue (uint32_t address, uint16_t value)
MEM_ERROR FillMemoryArea (uint32_t startAddress, uint32_t endAddress, uint8_t value)
MEM_ERROR FillMemoryArea (uint32_t startAddress, uint32_t endAddress, uint16_t value)
MEM_ERROR FillMemoryArea (uint32_t startAddress, uint32_t endAddress, uint8_t(*dataFunction)(uint32_t address))
MEM_ERROR FillMemoryArea (uint32_t startAddress, uint32_t endAddress, uint16_t(*dataFunction)(uint32_t address))
MEM_ERROR VerifyMemoryArea (uint32_t startAddress, uint32_t endAddress, uint16_t expectedValue)
MEM_ERROR VerifyMemoryArea (uint32_t startAddress, uint32_t endAddress, uint8_t expectedValue)
MEM_ERROR VerifyMemoryArea (uint32_t startAddress, uint32_t endAddress, uint8_t(*dataFunction)(uint32_t address))
MEM_ERROR VerifyMemoryArea (uint32_t startAddress, uint32_t endAddress, uint16_t(*dataFunction)(uint32_t address))
MEM_ERROR FillWithZeros ()
MEM_ERROR FillWithZerosAndVerifyRead ()
MEM_ERROR FillWithOnes ()
MEM_ERROR FillMemoryWithAscendingValues ()
MEM_ERROR FillMemoryWithAscendingValuesAndVerifyRead (uint32_t *buffLen, const uint32_t *arguments)
MEM_ERROR FillMemoryWithAlternatingZeroAndOne ()
MEM_ERROR FillMemoryWithAlternatingOneAndZero ()
Static Public Member Functions
static bool IsInvalidAddress (uint32_t address, uint32_t size)
Protected Member Functions
void InitCounter ()
void InitArguments ()
Protected Attributes
uint8_t write_mode
uint16_t len
char STRING_BUFFER [STRING_BUFFER_SIZE]
TimeMeasurement m_timeMeasurement
uint32_t m_MMIOStartAddress
InterfaceWrapper * m_InterfaceWrapper
uint16_t start_value = 0x0
uint32_t start_adr = 0x0
uint32_t end_adr = 0x0
char SRAM_BUFFER [40960] {}
char * srambp {}
uint32_t total_one
uint32_t total_zero
uint32_t flipped_one
uint32_t flipped_zero
MemoryModule & m_MemoryModule
Detailed Description
Definition at line 40 of file MemoryController.h.
Constructor & Destructor Documentation
MemoryController()
MemoryController::MemoryController (InterfaceWrapper * interfaceWrapper, MemoryModule & memoryModule) explicit
Definition at line 16 of file MemoryController.cpp.
        : write_mode(0xFF), len(0), STRING_BUFFER(""),
          m_MMIOStartAddress(MEMORY_BANK_ADDRESS),
          srambp(nullptr), total_one(0), total_zero(0),
          flipped_one(0), flipped_zero(0), m_MemoryModule(memoryModule)
{
    m_InterfaceWrapper = interfaceWrapper;
}
References m_InterfaceWrapper.
~MemoryController()
MemoryController::~MemoryController () virtual default
Member Function Documentation
FillMemoryArea() [1/4]
MEM_ERROR MemoryController::FillMemoryArea (uint32_t startAddress, uint32_t endAddress, uint16_t value)
Definition at line 48 of file MemoryController.cpp.
{
    for (uint32_t adr = startAddress; adr < endAddress; adr++)
    {
        MEM_ERROR ret = Write16BitWord(adr, value);
        if (ret != MemoryErrorHandling::MEM_NO_ERROR)
            return ret;
    }
    return MemoryErrorHandling::MEM_NO_ERROR;
}
References MemoryErrorHandling::MEM_NO_ERROR, and Write16BitWord().
FillMemoryArea() [2/4]
MEM_ERROR MemoryController::FillMemoryArea (uint32_t startAddress, uint32_t endAddress, uint16_t(*)(uint32_t address) dataFunction)
FillMemoryArea() [3/4]
MEM_ERROR MemoryController::FillMemoryArea (uint32_t startAddress, uint32_t endAddress, uint8_t value)
Definition at line 37 of file MemoryController.cpp.
{
    for(uint32_t adr = startAddress; adr < endAddress; adr++)
    {
        MEM_ERROR ret = Write8BitWord(adr, value);
        if (ret != MemoryErrorHandling::MEM_NO_ERROR)
            return ret;
    }
    return MemoryErrorHandling::MEM_NO_ERROR;
}
References MemoryErrorHandling::MEM_NO_ERROR, and Write8BitWord().
Referenced by FillMemoryWithAlternatingOneAndZero(), FillMemoryWithAlternatingZeroAndOne(), FillMemoryWithAscendingValues(), FillMemoryWithAscendingValuesAndVerifyRead(), FillWithOnes(), FillWithZeros(), and FillWithZerosAndVerifyRead().
FillMemoryArea() [4/4]
MEM_ERROR MemoryController::FillMemoryArea (uint32_t startAddress, uint32_t endAddress, uint8_t(*)(uint32_t address) dataFunction)
FillMemoryWithAlternatingOneAndZero()
MEM_ERROR MemoryController::FillMemoryWithAlternatingOneAndZero ()
Definition at line 307 of file MemoryController.cpp.
{
    // reset the counter for statistical analysis
    InitCounter();
    // reset the m_arguments
    InitArguments();
    // reset the counter for statistical analysis // TODO was hat es mit den counter auf sich?
    InitCounter();
    // reset the m_arguments
    InitArguments();
    if (m_MemoryModule.GetBitWidth() == 16)
        return FillMemoryArea(0, m_MemoryModule.GetMemorySize(), static_cast<uint16_t>(0xAAAA));
    else if(m_MemoryModule.GetBitWidth() == 8)
        return FillMemoryArea(0, m_MemoryModule.GetMemorySize(), static_cast<uint8_t>(0xAA));
    return MemoryErrorHandling::MEM_BIT_LEN_NOT_SUPPORTED;
}
References FillMemoryArea(), MemoryModule::GetBitWidth(), MemoryModule::GetMemorySize(), InitArguments(), InitCounter(), m_MemoryModule, and MemoryErrorHandling::MEM_BIT_LEN_NOT_SUPPORTED.
Referenced by CommandLineParser::executeCommand().
FillMemoryWithAlternatingZeroAndOne()
MEM_ERROR MemoryController::FillMemoryWithAlternatingZeroAndOne ()
Definition at line 283 of file MemoryController.cpp.
{
    // reset the counter for statistical analysis
    InitCounter();
    // reset the m_arguments
    InitArguments();
    // reset the counter for statistical analysis // TODO was hat es mit den counter auf sich?
    InitCounter();
    // reset the m_arguments
    InitArguments();
    if (m_MemoryModule.GetBitWidth() == 16)
        return FillMemoryArea(0, m_MemoryModule.GetMemorySize(), static_cast<uint16_t>(0x5555));
    else if (m_MemoryModule.GetBitWidth() == 8)
        return FillMemoryArea(0, m_MemoryModule.GetMemorySize(), static_cast<uint8_t>(0x55));
    return MemoryErrorHandling::MEM_BIT_LEN_NOT_SUPPORTED;
}
References FillMemoryArea(), MemoryModule::GetBitWidth(), MemoryModule::GetMemorySize(), InitArguments(), InitCounter(), m_MemoryModule, and MemoryErrorHandling::MEM_BIT_LEN_NOT_SUPPORTED.
Referenced by CommandLineParser::executeCommand().
FillMemoryWithAscendingValues()
MEM_ERROR MemoryController::FillMemoryWithAscendingValues ()
Definition at line 206 of file MemoryController.cpp.
{
    // reset the counter for statistical analysis
    InitCounter();
    // reset the m_arguments
    InitArguments();
    MEM_ERROR ret = MemoryErrorHandling::MEM_BIT_LEN_NOT_SUPPORTED;
    if (m_MemoryModule.GetBitWidth() == 16)
        ret = FillMemoryArea(0, m_MemoryModule.GetMemorySize(), [](uint32_t address){
            return static_cast<uint16_t>(address % 0xFFFF);
        });
    else if(m_MemoryModule.GetBitWidth() == 8)
        ret = FillMemoryArea(0, m_MemoryModule.GetMemorySize(), [](uint32_t address){
            return static_cast<uint16_t>(address % 0xFFFF);
        });
    if (ret != MemoryErrorHandling::MEM_NO_ERROR)
        return ret;
    return MemoryErrorHandling::MEM_NO_ERROR;
}
References FillMemoryArea(), MemoryModule::GetBitWidth(), MemoryModule::GetMemorySize(), InitArguments(), InitCounter(), m_MemoryModule, MemoryErrorHandling::MEM_BIT_LEN_NOT_SUPPORTED, and MemoryErrorHandling::MEM_NO_ERROR.
Referenced by CommandLineParser::executeCommand().
FillMemoryWithAscendingValuesAndVerifyRead()
MEM_ERROR MemoryController::FillMemoryWithAscendingValuesAndVerifyRead (uint32_t * buffLen, const uint32_t * arguments)
Definition at line 230 of file MemoryController.cpp.
{
    // reset the counter for statistical analysis
    InitCounter();
    // reset the m_arguments
    InitArguments();
#if MEM_ACCESS_WIDTH_BIT == 16
#elif MEM_ACCESS_WIDTH_BIT == 8
    auto countFunction = [](uint32_t address)
    {
        return static_cast<uint8_t>(address % 0xFF);
    };
#endif // MEM_ACCESS_WIDTH_BIT == 16
    MEM_ERROR ret = MemoryErrorHandling::MEM_BIT_LEN_NOT_SUPPORTED;
    if (m_MemoryModule.GetBitWidth() == 16)
    {
        ret = FillMemoryArea(0, m_MemoryModule.GetMemorySize(), [](uint32_t address)
        {
            return static_cast<uint16_t>(address % 0xFFFF);
        });
    }
    else if (m_MemoryModule.GetBitWidth() == 8)
    {
        ret = FillMemoryArea(0, m_MemoryModule.GetMemorySize(), [](uint32_t address)
        {
            return static_cast<uint8_t>(address % 0xFF);
        });
    }
    if (ret != MemoryErrorHandling::MEM_NO_ERROR)
        return ret;
    if (m_MemoryModule.GetBitWidth() == 16)
        return VerifyMemoryArea(0, m_MemoryModule.GetMemorySize(), [](uint32_t address)
        {
            return static_cast<uint16_t>(address % 0xFFFF);
        });
    else if (m_MemoryModule.GetBitWidth() == 8)
        return VerifyMemoryArea(0, m_MemoryModule.GetMemorySize(), [](uint32_t address)
        {
            return static_cast<uint8_t>(address % 0xFF);
        });
    return MemoryErrorHandling::MEM_BIT_LEN_NOT_SUPPORTED;
}
References FillMemoryArea(), MemoryModule::GetBitWidth(), MemoryModule::GetMemorySize(), InitArguments(), InitCounter(), m_MemoryModule, MemoryErrorHandling::MEM_BIT_LEN_NOT_SUPPORTED, MemoryErrorHandling::MEM_NO_ERROR, and VerifyMemoryArea().
FillWithOnes()
MEM_ERROR MemoryController::FillWithOnes ()
Definition at line 186 of file MemoryController.cpp.
{
    // reset the counter for statistical analysis // TODO was hat es mit den counter auf sich?
    InitCounter();
    // reset the m_arguments
    InitArguments();
    if (m_MemoryModule.GetBitWidth() == 16)
        return FillMemoryArea(0, m_MemoryModule.GetMemorySize(), static_cast<uint16_t>(0xFFFF));
    else if (m_MemoryModule.GetBitWidth() == 8)
        return FillMemoryArea(0, m_MemoryModule.GetMemorySize(), static_cast<uint8_t>(0xFF));
    return MemoryErrorHandling::MEM_BIT_LEN_NOT_SUPPORTED;
}
References FillMemoryArea(), MemoryModule::GetBitWidth(), MemoryModule::GetMemorySize(), InitArguments(), InitCounter(), m_MemoryModule, and MemoryErrorHandling::MEM_BIT_LEN_NOT_SUPPORTED.
Referenced by CommandLineParser::executeCommand().
FillWithZeros()
MEM_ERROR MemoryController::FillWithZeros ()
Definition at line 147 of file MemoryController.cpp.
{
        // reset the counter for statistical analysis // TODO was hat es mit den counter auf sich?
    InitCounter();
    // reset the m_arguments
    InitArguments();
    if(m_MemoryModule.GetBitWidth() == 16)
        return FillMemoryArea(0, m_MemoryModule.GetMemorySize(), static_cast<uint16_t>(0x0000));
    else if(m_MemoryModule.GetBitWidth() == 8)
        return FillMemoryArea(0, m_MemoryModule.GetMemorySize(), static_cast<uint8_t>(0x00));
    return MemoryErrorHandling::MEM_BIT_LEN_NOT_SUPPORTED;
}
References FillMemoryArea(), MemoryModule::GetBitWidth(), MemoryModule::GetMemorySize(), InitArguments(), InitCounter(), m_MemoryModule, and MemoryErrorHandling::MEM_BIT_LEN_NOT_SUPPORTED.
Referenced by CommandLineParser::executeCommand().
FillWithZerosAndVerifyRead()
MEM_ERROR MemoryController::FillWithZerosAndVerifyRead ()
Definition at line 162 of file MemoryController.cpp.
{
    MEM_ERROR ret = MemoryErrorHandling::MEM_BIT_LEN_NOT_SUPPORTED;
    if(m_MemoryModule.GetBitWidth() == 16)
        ret = FillMemoryArea(0, m_MemoryModule.GetMemorySize(), static_cast<uint16_t>(0x0000));
    else if(m_MemoryModule.GetBitWidth() == 8)
        ret = FillMemoryArea(0, m_MemoryModule.GetMemorySize(), static_cast<uint8_t>(0x00));
    if (ret != MemoryErrorHandling::MEM_NO_ERROR)
        return ret;
    if(m_MemoryModule.GetBitWidth() == 16)
        return VerifyMemoryArea(0, m_MemoryModule.GetMemorySize(), static_cast<uint16_t>(0x00));
    else if(m_MemoryModule.GetBitWidth() == 8)
        return VerifyMemoryArea(0, m_MemoryModule.GetMemorySize(), static_cast<uint8_t>(0x000));
    return ret;
}
References FillMemoryArea(), MemoryModule::GetBitWidth(), MemoryModule::GetMemorySize(), m_MemoryModule, MemoryErrorHandling::MEM_BIT_LEN_NOT_SUPPORTED, MemoryErrorHandling::MEM_NO_ERROR, and VerifyMemoryArea().
InitArguments()
void MemoryController::InitArguments () protected
Definition at line 342 of file MemoryController.cpp.
{
    start_adr = 0;
    end_adr = 0;
    start_value = 0;
}
References end_adr, start_adr, and start_value.
Referenced by FillMemoryWithAlternatingOneAndZero(), FillMemoryWithAlternatingZeroAndOne(), FillMemoryWithAscendingValues(), FillMemoryWithAscendingValuesAndVerifyRead(), FillWithOnes(), and FillWithZeros().
InitCounter()
void MemoryController::InitCounter () protected
Definition at line 331 of file MemoryController.cpp.
{
    total_one = 0;
    total_zero = 0;
    flipped_one = 0;
    flipped_zero = 0;
}
References flipped_one, flipped_zero, total_one, and total_zero.
Referenced by FillMemoryWithAlternatingOneAndZero(), FillMemoryWithAlternatingZeroAndOne(), FillMemoryWithAscendingValues(), FillMemoryWithAscendingValuesAndVerifyRead(), FillWithOnes(), and FillWithZeros().
Initialize()
MEM_ERROR MemoryController::Initialize () virtual
Reimplemented in MemoryControllerParallel.
Definition at line 353 of file MemoryController.cpp.
{
    return MemoryErrorHandling::MEM_MEMORY_CONTROLLER_NOT_SPECIFIED;
}
References MemoryErrorHandling::MEM_MEMORY_CONTROLLER_NOT_SPECIFIED.
IsInvalidAddress()
bool MemoryController::IsInvalidAddress (uint32_t address, uint32_t size) static
Definition at line 348 of file MemoryController.cpp.
{
    return (address >= size) ?  true : false;
}
Referenced by RERAM_ADESTO_RM25C512C_LTAI_T::CreateReadMessage(), ReRAM_Fujitsu_MB85AS4MTPF_G_BCERE1::CreateReadMessage(), RERAM_ADESTO_RM25C512C_LTAI_T::CreateWriteMessage(), ReRAM_Fujitsu_MB85AS4MTPF_G_BCERE1::CreateWriteMessage(), MemoryControllerParallel::Read16BitWord(), MemoryControllerParallel::Read8BitWord(), MemoryControllerParallel::Write16BitWord(), and MemoryControllerParallel::Write8BitWord().
Read16BitWord()
MEM_ERROR MemoryController::Read16BitWord (uint32_t adr, uint16_t * value) virtual
Reimplemented in MemoryControllerSPI, and MemoryControllerParallel.
Definition at line 373 of file MemoryController.cpp.
{
    return MemoryErrorHandling::MEM_MEMORY_CONTROLLER_NOT_SPECIFIED;
}
References MemoryErrorHandling::MEM_MEMORY_CONTROLLER_NOT_SPECIFIED.
Referenced by MemoryTest::executeMemoryTest(), and VerifyMemoryArea().
Read8BitWord()
MEM_ERROR MemoryController::Read8BitWord (uint32_t adr, uint8_t * ret) virtual
Reimplemented in MemoryControllerSPI, and MemoryControllerParallel.
Definition at line 363 of file MemoryController.cpp.
{
    return MemoryErrorHandling::MEM_MEMORY_CONTROLLER_NOT_SPECIFIED;
}
References MemoryErrorHandling::MEM_MEMORY_CONTROLLER_NOT_SPECIFIED.
Referenced by VerifyMemoryArea().
VerifyMemoryArea() [1/4]
MEM_ERROR MemoryController::VerifyMemoryArea (uint32_t startAddress, uint32_t endAddress, uint16_t expectedValue)
Definition at line 100 of file MemoryController.cpp.
{
    for (uint32_t adr = startAddress; adr < endAddress; adr++)
    {
        uint16_t trueValue = 0;
        MEM_ERROR ret = Read16BitWord(adr, &trueValue);
        if (ret != MemoryErrorHandling::MEM_NO_ERROR)
            return ret;
        if(trueValue != expectedValue)
            return MemoryErrorHandling::MEM_NOT_WRITTEN;
    }
    return MemoryErrorHandling::MEM_NO_ERROR;
}
References MemoryErrorHandling::MEM_NO_ERROR, MemoryErrorHandling::MEM_NOT_WRITTEN, and Read16BitWord().
Referenced by FillMemoryWithAscendingValuesAndVerifyRead(), and FillWithZerosAndVerifyRead().
VerifyMemoryArea() [2/4]
MEM_ERROR MemoryController::VerifyMemoryArea (uint32_t startAddress, uint32_t endAddress, uint16_t(*)(uint32_t address) dataFunction)
VerifyMemoryArea() [3/4]
MEM_ERROR MemoryController::VerifyMemoryArea (uint32_t startAddress, uint32_t endAddress, uint8_t expectedValue)
Definition at line 85 of file MemoryController.cpp.
{
    for (uint32_t adr = startAddress; adr < endAddress; adr++)
    {
        uint8_t trueValue = 0;
        MEM_ERROR ret = Read8BitWord(adr, &trueValue);
        if (ret != MemoryErrorHandling::MEM_NO_ERROR)
            return ret;
        if(trueValue != expectedValue)
            return MemoryErrorHandling::MEM_NOT_WRITTEN;
    }
    return MemoryErrorHandling::MEM_NO_ERROR;
}
References MemoryErrorHandling::MEM_NO_ERROR, MemoryErrorHandling::MEM_NOT_WRITTEN, and Read8BitWord().
VerifyMemoryArea() [4/4]
MEM_ERROR MemoryController::VerifyMemoryArea (uint32_t startAddress, uint32_t endAddress, uint8_t(*)(uint32_t address) dataFunction)
Write16BitWord()
MEM_ERROR MemoryController::Write16BitWord (uint32_t adr, uint16_t value) virtual
Reimplemented in MemoryControllerSPI, and MemoryControllerParallel.
Definition at line 368 of file MemoryController.cpp.
{
    return MemoryErrorHandling::MEM_MEMORY_CONTROLLER_NOT_SPECIFIED;
}
References MemoryErrorHandling::MEM_MEMORY_CONTROLLER_NOT_SPECIFIED.
Referenced by MemoryTest::executeMemoryTest(), FillMemoryArea(), and WriteSingleValue().
Write8BitWord()
MEM_ERROR MemoryController::Write8BitWord (uint32_t adr, uint8_t value) virtual
Reimplemented in MemoryControllerSPI, and MemoryControllerParallel.
Definition at line 358 of file MemoryController.cpp.
{
    return MemoryErrorHandling::MEM_MEMORY_CONTROLLER_NOT_SPECIFIED;
}
References MemoryErrorHandling::MEM_MEMORY_CONTROLLER_NOT_SPECIFIED.
Referenced by FillMemoryArea(), and WriteSingleValue().
WriteSingleValue() [1/2]
MEM_ERROR MemoryController::WriteSingleValue (uint32_t address, uint16_t value)
Definition at line 32 of file MemoryController.cpp.
{
    return Write16BitWord(address, value);
}
References Write16BitWord().
WriteSingleValue() [2/2]
MEM_ERROR MemoryController::WriteSingleValue (uint32_t address, uint8_t value)
Definition at line 27 of file MemoryController.cpp.
{
    return Write8BitWord(address, value);
}
References Write8BitWord().
Field Documentation
end_adr
uint32_t MemoryController::end_adr = 0x0 protected
Definition at line 97 of file MemoryController.h.
Referenced by InitArguments().
flipped_one
uint32_t MemoryController::flipped_one protected
Definition at line 107 of file MemoryController.h.
Referenced by InitCounter().
flipped_zero
uint32_t MemoryController::flipped_zero protected
Definition at line 108 of file MemoryController.h.
Referenced by InitCounter().
len
uint16_t MemoryController::len protected
Definition at line 87 of file MemoryController.h.
m_InterfaceWrapper
InterfaceWrapper* MemoryController::m_InterfaceWrapper protected
Definition at line 92 of file MemoryController.h.
Referenced by MemoryController().
m_MemoryModule
MemoryModule& MemoryController::m_MemoryModule protected
Definition at line 110 of file MemoryController.h.
Referenced by FillMemoryWithAlternatingOneAndZero(), FillMemoryWithAlternatingZeroAndOne(), FillMemoryWithAscendingValues(), FillMemoryWithAscendingValuesAndVerifyRead(), FillWithOnes(), FillWithZeros(), FillWithZerosAndVerifyRead(), MemoryControllerSPI::MemoryControllerSPI(), MemoryControllerSPI::Read16BitWord(), MemoryControllerSPI::Read8BitWord(), MemoryControllerParallel::Read8BitWord(), MemoryControllerSPI::Write16BitWord(), MemoryControllerSPI::Write8BitWord(), and MemoryControllerParallel::Write8BitWord().
m_MMIOStartAddress
uint32_t MemoryController::m_MMIOStartAddress protected
Definition at line 91 of file MemoryController.h.
Referenced by MemoryControllerParallel::Read16BitWord(), MemoryControllerParallel::Read8BitWord(), and MemoryControllerParallel::Write8BitWord().
m_timeMeasurement
TimeMeasurement MemoryController::m_timeMeasurement protected
Definition at line 89 of file MemoryController.h.
SRAM_BUFFER
char MemoryController::SRAM_BUFFER[40960] {} protected
Definition at line 100 of file MemoryController.h.
srambp
char* MemoryController::srambp {} protected
Definition at line 101 of file MemoryController.h.
start_adr
uint32_t MemoryController::start_adr = 0x0 protected
Definition at line 96 of file MemoryController.h.
Referenced by InitArguments().
start_value
uint16_t MemoryController::start_value = 0x0 protected
Definition at line 95 of file MemoryController.h.
Referenced by InitArguments().
STRING_BUFFER
char MemoryController::STRING_BUFFER[STRING_BUFFER_SIZE] protected
Definition at line 88 of file MemoryController.h.
total_one
uint32_t MemoryController::total_one protected
Definition at line 105 of file MemoryController.h.
Referenced by InitCounter().
total_zero
uint32_t MemoryController::total_zero protected
Definition at line 106 of file MemoryController.h.
Referenced by InitCounter().
write_mode
uint8_t MemoryController::write_mode protected
Definition at line 86 of file MemoryController.h.
The documentation for this class was generated from the following files:
/home/florianfrank/Documents/Research/Projects/PUFMem/stm_measurement_firmware/Inc/cpp/MemoryControllers/MemoryController.h
/home/florianfrank/Documents/Research/Projects/PUFMem/stm_measurement_firmware/Src/cpp/MemoryController/MemoryController.cpp